# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/James/ArduinoProjects/omnibot/TFSubscriber

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/James/ArduinoProjects/omnibot/TFSubscriber

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/James/ArduinoProjects/omnibot/TFSubscriber/CMakeFiles /mnt/c/Users/James/ArduinoProjects/omnibot/TFSubscriber/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/James/ArduinoProjects/omnibot/TFSubscriber/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TFSubscriber

# Build rule for target.
TFSubscriber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TFSubscriber
.PHONY : TFSubscriber

# fast build rule for target.
TFSubscriber/fast:
	$(MAKE) -f CMakeFiles/TFSubscriber.dir/build.make CMakeFiles/TFSubscriber.dir/build
.PHONY : TFSubscriber/fast

#=============================================================================
# Target rules for targets named XBee

# Build rule for target.
XBee: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 XBee
.PHONY : XBee

# fast build rule for target.
XBee/fast:
	$(MAKE) -f libs/xbee_ansic_library/src/xbee/CMakeFiles/XBee.dir/build.make libs/xbee_ansic_library/src/xbee/CMakeFiles/XBee.dir/build
.PHONY : XBee/fast

tfsubscriber.o: tfsubscriber.cpp.o

.PHONY : tfsubscriber.o

# target to build an object file
tfsubscriber.cpp.o:
	$(MAKE) -f CMakeFiles/TFSubscriber.dir/build.make CMakeFiles/TFSubscriber.dir/tfsubscriber.cpp.o
.PHONY : tfsubscriber.cpp.o

tfsubscriber.i: tfsubscriber.cpp.i

.PHONY : tfsubscriber.i

# target to preprocess a source file
tfsubscriber.cpp.i:
	$(MAKE) -f CMakeFiles/TFSubscriber.dir/build.make CMakeFiles/TFSubscriber.dir/tfsubscriber.cpp.i
.PHONY : tfsubscriber.cpp.i

tfsubscriber.s: tfsubscriber.cpp.s

.PHONY : tfsubscriber.s

# target to generate assembly for a file
tfsubscriber.cpp.s:
	$(MAKE) -f CMakeFiles/TFSubscriber.dir/build.make CMakeFiles/TFSubscriber.dir/tfsubscriber.cpp.s
.PHONY : tfsubscriber.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TFSubscriber"
	@echo "... XBee"
	@echo "... tfsubscriber.o"
	@echo "... tfsubscriber.i"
	@echo "... tfsubscriber.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

