atcmd.h
XBEE_ATCMD_DONE
Returned by an xbee_cmd_callback_fn() if the handle can be released.
XBEE_ATCMD_REUSE
Returned by an xbee_cmd_callback_fn() if more reponses are expected, or it has re-used the command handle.
XBEE_REMOTE_AT_OPT_QUEUE
Queue changes until ATAC command or another request with XBEE_REMOTE_AT_OPT_IMMEDIATE set.
Referenced by xbee_cmd_send.
XBEE_REMOTE_AT_OPT_IMMEDIATE
Apply changes immediately, don't wait for ATAC command.
Referenced by xbee_cmd_send.
XBEE_CMD_RESP_MASK_STATUS
XBEE_CMD_RESP_ATND_RSSI_INVALID
XBEE_CMD_RESP_FLAG_TIMEOUT
XBEE_CMD_FLAG_REMOTE
set in xbee_cmd_set_target() and used as a quick test for remote vs.
local in xbee_cmd_send()
Referenced by xbee_cmd_send.
XBEE_CMD_FLAG_QUEUE_CHANGE
queue change until ATAC or another request w/o this flag
Referenced by xbee_cmd_send.
XBEE_CMD_FLAG_REUSE_HANDLE
don't automatically release non-response requests (no callback) after sending (necessary for functions that reuse handle)
XBEE_CMD_FLAG_USER_MASK
mask of flags user can set (passed into xbee_cmd_set_flags)
XBEE_CMD_REQUEST_TABLESIZE
Maximum number of outstanding requests.
Two should be sufficient in most (all?) cases. One might even be enough if space is tight.
Referenced by _xbee_cmd_handle_to_address.
XBEE_CMD_MAX_PARAM_LENGTH
Maximum number of bytes in the parameter sent to a command.
The NI command takes a 20-byte string. ATZT is 48 bytes, ATZU is 22. Platforms can override this when limiting to AT commands with shorter parameters (e.g., 16 bytes when not using the certificate parameters).
Referenced by xbee_cmd_set_param_bytes, xbee_cmd_set_param_str.
XBEE_CMD_REMOTE_TIMEOUT
Timeout (in seconds) to wait for a response to a remote command.
Set to a high value to allow for a sleeping end device.
XBEE_CMD_LOCAL_TIMEOUT
Timeout (in seconds) to wait for a response to a local command.
XBEE_CMD_ATEO_INSECURE_JOIN
XBEE_CMD_ATEO_USE_TRUST_CENTER
XBEE_CMD_ATEO_USE_HASH_LINK_KEY
XBEE_CMD_ATEO_USE_AUTHENTICATION
XBEE_AT_RESP_STATUS
Macro for checking the status byte of an AT response.
If this library is compiled without DigiMesh support, we can use a simpler test.
XBEE_ATCMD_REG
Macro used in creating command list tables.
This macro does not set a callback. c1 first character of AT command c2 second character of AT command type one of xbee_command_list_type enumerated values: XBEE_CLT_NONE - no action except to issue the command. 'obj' and 'field' parameters are ignored. XBEE_CLT_COPY - copy response data directly, followed by 0x00 to fill the target element XBEE_CLT_COPY_PAD_LEFT - copy response data directly, padding to the left with 0x00 to fill target element XBEE_CLT_COPY_BE - copy numeric data to host byte order XBEE_CLT_SET - set command parameter directly XBEE_CLT_SET_STR - set command parameter as null- terminated string. XBEE_CLT_SET_BE - set numeric command parameter obj typedef name of object at base address field field in obj in which to store result The 'type' parameter allows for either setting the data in the base structure as the command parameter (XBEE_CLT_SET*) or the converse, which is copying the command result back to the base structure (XBEE_CLT_COPY*). xbee_atcmd_reg_t record for constructing command list tables XBEE_ATCMD_REG_CB, XBEE_ATCMD_REG_SET_8
XBEE_ATCMD_REG_CB
Macro used in creating command list tables.
c1 first character of AT command c2 second character of AT command cb callback function (prototype xbee_command_list_fn) flags 8-bit flags for callback (arbitrary). xbee_atcmd_reg_t record for constructing command list tables XBEE_ATCMD_REG
XBEE_ATCMD_REG_MOVE_THEN_CB
Macro used in creating command list tables.
This is a combination of XBEE_ATCMD_REG (moving data automatically) and XBEE_ATCMD_REG_CB (calling a callback function). The callback function is invoked after the data move. c1 first character of AT command c2 second character of AT command type one of xbee_command_list_type enumerated values: XBEE_CLT_NONE - no action except to issue the command. 'obj' and 'field' parameters are ignored. XBEE_CLT_COPY - copy response data directly, followed by 0x00 to fill the target element XBEE_CLT_COPY_PAD_LEFT - copy response data directly, padding to the left with 0x00 to fill target element XBEE_CLT_COPY_BE - copy numeric data to host byte order XBEE_CLT_SET - set command parameter directly XBEE_CLT_SET_STR - set command parameter as null- terminated string. XBEE_CLT_SET_BE - set numeric command parameter obj typedef name of object at base address field field in obj in which to store result cb callback function (prototype xbee_command_list_fn) flags 8-bit flags for callback (arbitrary). xbee_atcmd_reg_t record for constructing command list tables XBEE_ATCMD_REG, XBEE_ATCMD_REG_CB
XBEE_ATCMD_REG_SET_8
Macro used in creating command list tables.
This macro does not set a callback. c1 first character of AT command c2 second character of AT command value unsigned 8-bit value (compile-time constant) to set. xbee_atcmd_reg_t record for constructing command list tables XBEE_ATCMD_REG
XBEE_ATCMD_REG_END
Macro used in creating command list tables.
Used to terminate table, with no special final callback. This must be the last entry if used, or XBEE_ATCMD_REG_END_CB must be used.
XBEE_ATCMD_REG_END_CMD
Macro used in creating command list tables.
Used to terminate table, with a command (usually ND or WR). This must be the last entry if used.
XBEE_ATCMD_REG_END_CB
Macro used in creating command list tables.
Used to terminate table, with a final callback. This must be the last entry if used, or XBEE_ATCMD_REG_END must be used. cb callback function (prototype xbee_command_list_fn). The 'response' parameter to the callback will be the final command response received. flags 8-bit flags for callback (arbitrary).
XBEE_ATCMD_REG_VALID
xbee_cmd_list_status
XBEE_CMD_REQUEST_EMPTY
Is entry index available (unused)?
XBEE_CMD_REQUEST_HANDLE
Return the handle for entry index (combination of index and .sequence member of entry).
XBEE_FRAME_HANDLE_LOCAL_AT
XBEE_FRAME_HANDLE_REMOTE_AT
xbee_zcl_identify
Programs with the ZCL Identify Server Cluster can call this macro in their main loop to have the XBee module's association LED flash fast (100ms cycle) when in Identify Mode.
xbee device to identify xbee_identify, zcl_identify_isactive, ZCL_CLUST_ENTRY_IDENTIFY_SERVER
xbee_at_resp_status
Mask to ignore extra bits used in the status response.
xbee_command_list_status
xbee_command_list_type
No default action. Often used for callbacks.
typedef int(* xbee_cmd_callback_fn) (const xbee_cmd_response_t FAR *response))(const xbee_cmd_response_t FAR *response)
Callback registered to an AT Command with xbee_cmd_set_callback().
It should not modify the contents of the xbee_cmd_response_t structure passed to it. It should return either XBEE_ATCMD_DONE or XBEE_ATCMD_REUSE.View the help on xbee_cmd_response_t for details on the members of that structure. response response received for AT Command XBEE_ATCMD_DONE done with the request handle XBEE_ATCMD_REUSE more responses are expected, or the request handle will be reused xbee_cmd_set_callback(), xbee_cmd_response_t
typedef PACKED_STRUCT xbee_header_local_at_req
Header for AT Commands sent to the local (serially-attached) XBee.
typedef PACKED_STRUCT xbee_header_remote_at_req
Header to AT Commands sent to a remote XBee on the network.
typedef PACKED_STRUCT xbee_header_local_at_resp
typedef PACKED_STRUCT xbee_header_remote_at_resp
typedef PACKED_STRUCT xbee_frame_local_at_resp
Response to an AT Command sent to the local serially-connected XBee.
typedef PACKED_STRUCT xbee_frame_remote_at_resp
Response to an AT Command sent to a remote XBee.
typedef void(* xbee_command_list_fn) (const xbee_cmd_response_t FAR *response, const struct xbee_atcmd_reg_t FAR *reg, void FAR *base))(const xbee_cmd_response_t FAR *response, const struct xbee_atcmd_reg_t FAR *reg, void FAR *base)
Callback registered for individual command list commands.
response response received for AT Command. From this, the context field points to the start of the entire set of commands in the list being processed. reg Table element for this command. Usually, the callback will dereference reg->context to find any required auxiliary data for processing this command. base Base address of structure to populate with response value (typical use). This callback is called for a command response, and is intended to be used for manipulating the raw response data into something suitable for the application. There is no corresponding callback for a request (i.e. called before setting parameter data); the application is expected to perform setting parameter manipulation before invoking xbee_cmd_list_execute().
uint8_t frame_id
1 to 255, or 0 to suppress the Transmit Status response
ID from request, used to match response to request.
Referenced by _xbee_cmd_handle_response.
uint8_t command
two-character AT Command
Command from original request.
Referenced by _xbee_cmd_handle_response, _xbee_cmd_list_callback, zcl_default_response.
xbee_header_local_at_req_t
addr64 ieee_address
64-bit IEEE address (big-endian) of target
64-bit IEEE address (big-endian) of source.64-bit IEEE address (big-endian) of responder.
uint16_t network_address_be
16-bit network address (big-endian) of target
16-bit network address (big-endian) of source.16-bit network address (big-endian) of responder.
uint8_t options
Options byte (see XBEE_REMOTE_AT_OPT_* macros)
combination of XBEE_TX_OPT_* macrosbitfield, see XBEE_RX_OPT_xxx macros
Referenced by xbee_ota_server_cmd.
xbee_header_remote_at_req_t
uint8_t status
See enum xbee_at_resp_status.
Note that DigiMesh uses the upper nibble for additional flags use XBEE_AT_RESP_STATUS() macro when comparing this field to the xbee_at_resp_status enum.
Referenced by _xbee_cmd_handle_response, _xbee_cmd_modem_status, _zcl_onoff_handler, _zcl_write_attributes, xbee_ser_get_cts, xbee_ser_set_rts, zcl_comm_response, zcl_default_response, zcl_encode_attribute_value, zcl_invalid_command.
xbee_header_local_at_resp_t
xbee_header_remote_at_resp_t
uint8_t value[1]
First byte of multi-byte value.
variable length, only if ZCL_STATUS_SUCCESSCached value.
Referenced by _xbee_cmd_handle_response, _zcl_comm_startup_control_set, zcl_check_minmax, zcl_print_array_value, zcl_print_struct_value.
xbee_frame_local_at_resp_t
xbee_frame_remote_at_resp_t
FAR xbee_cmd_request_t xbee_cmd_request_table[XBEE_CMD_REQUEST_TABLESIZE][XBEE_CMD_REQUEST_TABLESIZE]
Table used to keep track of outstanding requests.
Referenced by _xbee_cmd_handle_to_address.
int xbee_cmd_list_execute(xbee_dev_t *xbee, xbee_command_list_context_t FAR *clc, const xbee_atcmd_reg_t FAR *list, void FAR *base, const wpan_address_t FAR *address)
Execute a list of AT commands.
xbee Device to execute commands clc List head to set up. This must be static since callback functions access it asynchronously. list First entry of list of commands to execute. The list must be terminated by either XBEE_ATCMD_REG_END or XBEE_ATCMD_REG_END_CB. List entries are created using XBEE_ATCMD_REG macros etc. base Base address of a structure to fill in with command results or as a source of values to set. address Remote address, or NULL if local device. 0 started sending commands from the list -ENOSPC the AT command table is full (increase the compile-time macro XBEE_CMD_REQUEST_TABLESIZE) -EINVAL an invalid parameter was passed to the function xbee_cmd_list_status()
enum xbee_command_list_status() xbee_cmd_list_status(xbee_command_list_context_t FAR *clc)
Determine status of command list execution.
clc List head passed to xbee_cmd_list_execute(). XBEE_COMMAND_LIST_RUNNING currently executing commands XBEE_COMMAND_LIST_DONE successfully completed XBEE_COMMAND_LIST_TIMEOUT timed out XBEE_COMMAND_LIST_ERROR completed with error(s) xbee_cmd_list_execute()
Referenced by xbee_cmd_query_status, xbee_io_query_status.
int xbee_cmd_tick(void)
This function should be called periodically (at least every few seconds) to expire old entries from the AT Command Request table.
>0 number of requests expired 0 none of the requests in the table expired
References FAR.
Referenced by xbee_cmd_query_status, xbee_io_query_status.
xbee_cmd_request_t FAR * _xbee_cmd_handle_to_address(int16_t handle)
Convert a handle (16-bit int) to a pointer into the command request table. Ensures that the handle is valid (correct index and sequence bytes). handle Handle returned from xbee_cmd_create(). Pointer into the request table or NULL if handle is invalid. xbee_cmd_create()
References FAR, xbee_cmd_request_table, XBEE_CMD_REQUEST_TABLESIZE.
Referenced by xbee_cmd_release_handle, xbee_cmd_send, xbee_cmd_set_callback, xbee_cmd_set_command, xbee_cmd_set_param, xbee_cmd_set_target.
int xbee_cmd_init_device(xbee_dev_t *xbee)
Initialize the AT Command layer for an XBee device.
You need to call this function before any of the other xbee_cmd_* functions. xbee XBee device on which to enable the AT Command layer. This function will automatically call xbee_cmd_query_device if it hasn't already been called for this device. 0 the XBee device was successfully configured to send and receive AT commands -EINVAL an invalid parameter was passed to the function xbee_cmd_query_device(), xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References EINVAL, xbee_dev_t::flags, xbee_cmd_query_device, XBEE_DEV_FLAG_CMD_INIT, XBEE_DEV_FLAG_QUERY_BEGIN.
int xbee_cmd_query_device(xbee_dev_t *xbee, uint_fast8_t refresh)
Learn about the underlying device by sending a series of commands and storing the results in the xbee_dev_t.
This function will likely get called by the XBee stack at some point in the startup/initialization phase.Use xbee_cmd_query_status() to check on the progress of querying the device. xbee XBee device to query. refresh if non-zero, just refresh the volatile values (e.g., network settings, as opposed to device serial number) 0 Started querying device. -EBUSY Transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal). xbee_cmd_init_device(), xbee_cmd_query_status()
References EINVAL, xbee_dev_t::flags, XBEE_ATCMD_REG_REFRESH_IDX, XBEE_DEV_FLAG_QUERY_INPROGRESS, XBEE_DEV_FLAG_QUERY_REFRESH.
Referenced by _xbee_cmd_modem_status, xbee_cmd_init_device.
int xbee_cmd_query_status(xbee_dev_t *xbee)
Check the status of querying an XBee device, as initiated by xbee_cmd_query_device().
xbee device to check 0 query completed -EINVAL xbee is NULL -EBUSY query underway -ETIMEDOUT query timed out -EIO halted, but query may not have completed (unexpected response)
References EINVAL, xbee_cmd_list_status, xbee_cmd_tick.
int16_t xbee_cmd_create(xbee_dev_t *xbee, const char FAR command[3])
Allocate an AT Command request.
xbee XBee device to use as the target (local) or to send through (remote). This function will automatically call xbee_cmd_init() if it hasn't already been called for this device. command Two-letter AT Command to send (e.g., "VR", "NI", etc.). >0 a "handle" to a request that can be built up and sent to a local (serially-attached) or remote XBee module. -ENOSPC the AT command table is full (increase the compile-time macro XBEE_CMD_REQUEST_TABLESIZE) -EINVAL an invalid parameter was passed to the function xbee_cmd_init_device(), xbee_cmd_query_device(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
Referenced by xbee_io_set_options.
int _xbee_cmd_release_request(xbee_cmd_request_t FAR *request)
Release an entry from the request table by marking it as available.
For internal driver use only userspace code should use xbee_cmd_release_handle() instead. request Address of the table entry. 0 request freed -EINVAL address (request) is not valid xbee_cmd_create(), xbee_cmd_release_handle() Todoadd bounds checking on request to make sure it's in the table?
References EINVAL.
Referenced by xbee_cmd_release_handle.
int xbee_cmd_release_handle(int16_t handle)
Release an entry from the request table by marking it as available.
handle handle to the request (as returned by xbee_cmd_create) 0 request freed -EINVAL handle is not valid xbee_cmd_create(), xbee_cmd_release_handle()
References _xbee_cmd_handle_to_address, _xbee_cmd_release_request.
int xbee_cmd_set_command(int16_t handle, const char FAR command[3])
Change the command associated with a request.
handle handle to the request, as returned by xbee_cmd_create() command two-letter AT Command to send (e.g., "VR", "NI", etc.) 0 command changed -EINVAL handle is not valid xbee_cmd_create(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References _xbee_cmd_handle_to_address, EINVAL, FAR.
int xbee_cmd_set_callback(int16_t handle, xbee_cmd_callback_fn callback, void FAR *context)
Associate a callback with a given AT Command request.
handle Handle to the request, as returned by xbee_cmd_create(). callback Callback function to receive the AT Command response. This function should take a single parameter (pointer to an xbee_cmd_response_t) and return either XBEE_ATCMD_DONE (if done with the request handle) or XBEE_ATCMD_REUSE (if more responses are expected, or the request handle is going to be reused). intatcmd_callback(constxbee_cmd_response_tFAR*response) context Context (or "userdata") value to pass to the callback along with the AT Command response when it arrives. Should be set to NULL if not used. 0 callback set -EINVAL handle is not valid xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References _xbee_cmd_handle_to_address, EINVAL, FAR.
int xbee_cmd_set_target(int16_t handle, const addr64 FAR *ieee, uint16_t network_address)
Associate a remote XBee device with a given AT Command request.
By default, xbee_cmd_create() configures the request as a local AT Command for the serially-attached XBee module. Use this function to send the command to a remote device. handle Handle to the request, as returned by xbee_cmd_create(). ieee Pointer to 64-bit IEEE hardware address of target, or NULL to switch back to the local XBee device. WPAN_IEEE_ADDR_BROADCAST for broadcast.WPAN_IEEE_ADDR_COORDINATOR for the coordinator (use WPAN_NET_ADDR_UNDEFINED for the network address).WPAN_IEEE_ADDR_UNDEFINED to use the 16-bit network address. network 16-bit network address of target. WPAN_NET_ADDR_UNDEFINED if the node's network address isn't known or this is a DigiMesh network.WPAN_NET_ADDR_COORDINATOR for the coordinator (use the coordinator's actual IEEE address for the ieee parameter).WPAN_NET_ADDR_BCAST_NOT_ASLEEP to broadcast to all nodes that aren't sleeping.WPAN_NET_ADDR_BCAST_ROUTERS to broadcast to the coordinator and all routers. 0 target set -EINVAL handle is not valid -ENOSYS function not implemented (XBEE_CMD_DISABLE_REMOTE defined) xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References _xbee_cmd_handle_to_address, EINVAL, ENOSYS, FAR.
Referenced by xbee_io_set_options.
int xbee_cmd_set_flags(int16_t handle, uint16_t flags)
Set the flags for a given AT Command request.
handle Handle to the request, as returned by xbee_cmd_create(). flags One or more of the following: XBEE_CMD_FLAG_QUEUE_CHANGE don't apply changes until ATAC or another command without this flag is sent 0 flags set -EINVAL handle is not valid xbee_cmd_clear_flags
int xbee_cmd_clear_flags(int16_t handle, uint16_t flags)
Clear the flags for a given AT Command request.
handle Handle to the request, as returned by xbee_cmd_create(). flags One or more of the following: XBEE_CMD_FLAG_QUEUE_CHANGE don't apply changes until ATAC or another command without this flag is sent 0 flags cleared -EINVAL handle is not valid xbee_cmd_set_flags
int xbee_cmd_set_param(int16_t handle, uint32_t value)
Set the parameter (up to 32-bits) for a given AT Command request.
handle Handle to the request, as returned by xbee_cmd_create(). value Value to use as the parameter to the AT Command. For negative values, or values > 0xFFFFFFFF, use xbee_cmd_set_param_bytes(). For string parameters (e.g., for the "NI" command), use xbee_cmd_set_param_str(). 0 parameter set -EINVAL handle is not valid xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References _xbee_cmd_encode_param, _xbee_cmd_handle_to_address, EINVAL, FAR.
Referenced by xbee_io_set_options.
int xbee_cmd_set_param_bytes(int16_t handle, const void FAR *data, uint8_t length)
Set the parameter for a given AT Command request to a sequence of bytes.
handle Handle to the request, as returned by xbee_cmd_create(). data Pointer to bytes (MSB-first) to copy into request. length Number of bytes to copy. 0 < length <= XBEE_CMD_MAX_PARAM_LENGTH 0 parameter set -EINVAL handle or length is not valid -EMSGSIZE length is greater than XBEE_CMD_MAX_PARAM_LENGTH xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_str(), xbee_cmd_send()
References FAR, XBEE_CMD_MAX_PARAM_LENGTH.
Referenced by xbee_cmd_set_param_str.
int xbee_cmd_set_param_str(int16_t handle, const char FAR *str)
Set a string parameter for a given AT Command request (e.g., the "NI" node identifier command).
handle Handle to the request, as returned by xbee_cmd_create(). str String to use as the parameter. Must be less than XBEE_CMD_MAX_PARAM_LENGTH characters long. 0 parameter set -EINVAL handle is not valid -EMSGSIZE str is more than XBEE_CMD_MAX_PARAM_LENGTH characters. xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_send()
References EMSGSIZE, length, XBEE_CMD_MAX_PARAM_LENGTH, xbee_cmd_set_param_bytes.
int xbee_cmd_send(int16_t handle)
Send an AT Command to a local or remote XBee device.
handle Handle to the request, as returned by xbee_cmd_create(). 0 frame sent -EINVAL handle is not valid -EBUSY transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal). If the request does not have a callback set, it will be automatically released if xbee_cmd_send() returns 0. xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str()
References _xbee_cmd_handle_to_address, EINVAL, FAR, xbee_header_at_request_t::frame_type, htobe16, xbee_header_at_request_t::remote, XBEE_CMD_FLAG_QUEUE_CHANGE, XBEE_CMD_FLAG_REMOTE, XBEE_FRAME_REMOTE_AT_CMD, xbee_next_frame_id, XBEE_REMOTE_AT_OPT_IMMEDIATE, XBEE_REMOTE_AT_OPT_QUEUE.
Referenced by xbee_io_set_options.
int xbee_cmd_simple(xbee_dev_t *xbee, const char FAR command[3], uint32_t value)
Simple interface for sending a command with a parameter to the local XBee without checking for a response.
xbee XBee device to use as the target. command Two-letter AT Command to send (e.g., "ID", "CH", etc.). value Value to use as the parameter to the AT Command. 0 command sent -EINVAL an invalid parameter was passed to the function -EBUSY transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal). xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_execute()
References PACKED_STRUCT.
int xbee_cmd_execute(xbee_dev_t *xbee, const char FAR command[3], const void FAR *data, uint8_t length)
Simple interface for sending a command with an optional parameter to the local XBee without checking for a response.
For an asynchronous method of sending AT commands and getting the response, see xbee_cmd_create, the xbee_cmd_set_* functions and xbee_cmd_send. xbee XBee device to use as the target. command Two-letter AT Command to send (e.g., "ID", "CH", etc.). data Optional big-endian (MSB-first) value to assign to command. Use NULL if command doesn't take a parameter. length Number of bytes in data; ignored if data is NULL. 0 command sent -EINVAL an invalid parameter was passed to the function -EBUSY transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal). xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_simple()
Referenced by xbee_disc_discover_nodes.
int _xbee_cmd_handle_response(xbee_dev_t *xbee, const void FAR *rawframe, uint16_t length, void FAR *context)
Callback handler registered for frame types XBEE_FRAME_LOCAL_AT_RESPONSE (0x88) and XBEE_FRAME_REMOTE_AT_RESPONSE (0x97).
Should only be called by the frame dispatcher and unit tests.See the function help for xbee_frame_handler_fn() for full documentation on this function's API.
References command, FAR, frame_id, status, value.
int _xbee_cmd_modem_status(xbee_dev_t *xbee, const void FAR *payload, uint16_t length, void FAR *context)
Receive modem status frames and update our network address (and payload size) on state changes.
xbee_frame_handler_fn()
References EINVAL, FAR, status, xbee_cmd_query_device, XBEE_MODEM_STATUS_COORD_START, XBEE_MODEM_STATUS_JOINED, XBEE_MODEM_STATUS_KEY_ESTABLISHED, XBEE_UNUSED_PARAMETER.
void xbee_identify(xbee_dev_t *xbee, bool_t identify)
Programs with the ZCL Identify Server Cluster can call this function in their main loop to have the XBee module's association LED flash fast (100ms cycle) when in Identify Mode.
xbee device to identify identify TRUE if XBee should be in identify mode xbee_zcl_identify, zcl_identify_isactive, ZCL_CLUST_ENTRY_IDENTIFY_SERVER