xbee_serial_dos.c
UART_RBR
UART_THR
UART_DLL
UART_IER
UART_DLM
UART_IIR
UART_FCR
UART_LCR
UART_MCR
UART_LSR
UART_MSR
UART_SCR
IER_NONE
IER_RX_DATA
IER_TX_EMPTY
IER_LSR_CHANGE
IER_MSR_CHANGE
IER_DEFAULT
FCR_DISABLE_FIFOS
FCR_ENABLE_FIFOS
FCR_CLEAR_RX_FIFO
FCR_CLEAR_TX_FIFO
FCR_DMA_MODE_0
FCR_DMA_MODE_1
FCR_ENABLE_64BYTE
FCR_INT_TRIGGER_1BYTE
FCR_INT_TRIGGER_4BYTE
FCR_INT_TRIGGER_8BYTE
FCR_INT_TRIGGER_14BYTE
FCR_DEFAULT
LCR_5BIT
LCR_6BIT
LCR_7BIT
LCR_8BIT
LCR_1STOP
LCR_2STOP
LCR_PARITY_NONE
LCR_PARITY_ODD
LCR_PARITY_EVEN
LCR_PARITY_MARK
LCR_PARITY_SPACE
LCR_BREAK_ENABLE
LCR_DIVISOR_LATCH
LCR_DEFAULT
MCR_NONE
MCR_DTR
MCR_RTS
MCR_OUT1
MCR_OUT2
MCR_LOOPBACK
MCR_AUTOFLOW
MCR_DEFAULT
MSR_CTS_CHANGED
MSR_DSR_CHANGED
MSR_RI_EDGE
MSR_CD_CHANGED
MSR_CTS
MSR_DSR
MSR_RI
MSR_CD
XBEE_SER_CHECK
CBUF_SIZE
xbee_serial_t* xbee_ser_com1
xbee_cbuf_t cb
uint8_t buf[CBUF_SIZE][CBUF_SIZE]
struct @0 txbuf
struct @0 rxbuf
void __interrupt __far xbee_ser_isr()
int xbee_ser_invalid(xbee_serial_t *serial)
Helper function used by other xbee_serial functions to validate the serial parameter.
Confirms that it is non-NULL and is set to a valid port. serial XBee serial port 1 serial is not a valid XBee serial port 0 serial is a valid XBee serial port
Referenced by _xbee_frame_load.
const char* xbee_ser_portname(xbee_serial_t *serial)
Returns a human-readable string describing the serial port.
For example, on a Windows machine this will be "COM1" or "COM999". On a Rabbit, it will be a single letter, "A" through "F". On Freescale HCS08, it will be something like "SCI1" or "SCI2". On POSIX, the name of the device (e.g., "/dev/ttyS0")Returns "(invalid)" if serial is invalid or not configured. serial port null-terminated string describing the serial port
int xbee_ser_write(xbee_serial_t *serial, const void FAR *buffer, int length)
Transmits length bytes from buffer to the XBee serial port serial.
serial XBee serial port buffer source of bytes to send length number of bytes to write >=0 The number of bytes successfully written to XBee serial port. -EINVAL serial is not a valid XBee serial port. -EIO I/O error attempting to write to serial port. xbee_ser_read(), xbee_ser_putchar(), xbee_ser_getchar()
Referenced by xbee_ser_putchar.
int xbee_ser_read(xbee_serial_t *serial, void FAR *buffer, int bufsize)
Reads up to bufsize bytes from XBee serial port serial and into buffer.
If there is no data available when the function is called, it will return immediately. serial XBee serial port buffer buffer to hold bytes read from XBee serial port bufsize maximum number of bytes to read >=0 The number of bytes read from XBee serial port. -EINVAL serial is not a valid XBee serial port. -EIO I/O error attempting to write to serial port. xbee_ser_write(), xbee_ser_putchar(), xbee_ser_getchar()
Referenced by xbee_ser_getchar.
int xbee_ser_putchar(xbee_serial_t *serial, uint8_t ch)
Transmits a single character, ch, to the XBee serial port serial.
serial XBee serial port ch character to send 0 Successfully sent (queued) character. -ENOSPC The write buffer is full and the character wasn't sent. -EINVAL serial is not a valid XBee serial port. xbee_ser_read(), xbee_ser_write(), xbee_ser_getchar()
int xbee_ser_getchar(xbee_serial_t *serial)
Reads a single character from the XBee serial port serial.
serial XBee serial port 0-255 character read from XBee serial port -ENODATA There aren't any characters in the read buffer. -EINVAL serial is not a valid XBee serial port. xbee_ser_read(), xbee_ser_write(), xbee_ser_getchar()
int xbee_ser_tx_free(xbee_serial_t *serial)
Returns the number of bytes of unused space in the serial transmit buffer for XBee serial port serial.
serial XBee serial port INT_MAX The buffer size is unlimited (or unknown). >=0 The number of bytes it would take to fill the XBee serial port's serial transmit buffer. -EINVAL serial is not a valid XBee serial port. xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_used(), xbee_ser_tx_flush()
int xbee_ser_tx_used(xbee_serial_t *serial)
Returns the number of queued bytes in the serial transmit buffer for XBee serial port serial.
serial XBee serial port 0 The buffer size is unlimited (or space used is unknown). >0 The number of bytes queued in the XBee serial port's serial transmit buffer. -EINVAL serial is not a valid XBee serial port. xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_free(), xbee_ser_tx_flush()
int xbee_ser_tx_flush(xbee_serial_t *serial)
Flushes (i.e., deletes and does not transmit) characters in the serial transmit buffer for XBee serial port serial.
serial XBee serial port 0 success -EINVAL serial is not a valid XBee serial port. xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_free(), xbee_ser_tx_used()
int xbee_ser_rx_free(xbee_serial_t *serial)
Returns the number of bytes of unused space in the serial receive buffer for XBee serial port serial.
serial XBee serial port INT_MAX The buffer size is unlimited (or unknown). >=0 The number of bytes it would take to fill the XBee serial port's serial receive buffer. -EINVAL serial is not a valid XBee serial port. xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_used(), xbee_ser_rx_flush()
int xbee_ser_rx_used(xbee_serial_t *serial)
Returns the number of queued bytes in the serial receive buffer for XBee serial port serial.
serial XBee serial port >=0 The number of bytes queued in the XBee serial port's serial transmit buffer. -EINVAL serial is not a valid XBee serial port. xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_free(), xbee_ser_rx_flush() Unlike xbee_ser_tx_used(), this function MUST return the number of bytes available. Some layers of the library wait until enough bytes are ready before continuing. We may expand on or replace this API. On some platforms (like Win32) we have to do some of our own buffering in order to peek at data in the serial receive buffer. Most of the driver only requires a check to see if some number of bytes are available or not. Consider changing the API to something like:intxbee_ser_rx_avail(xbee_serial_t*serial,uint8_tcount) returns TRUE if count bytes are available, FALSE otherwise.
int xbee_ser_rx_flush(xbee_serial_t *serial)
Deletes all characters in the serial receive buffer for XBee serial port serial.
serial XBee serial port 0 success -EINVAL serial is not a valid XBee serial port. xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_free(), xbee_ser_rx_used()
int xbee_ser_baudrate(xbee_serial_t *serial, uint32_t baudrate)
Change the baud rate of XBee serial port serial to baudrate bits/second.
serial XBee serial port baudrate Bits per second of serial data transfer speed. 0 Opened serial port within 5% of requested baudrate. -EINVAL serial is not a valid XBee serial port. -EIO Can't open serial port within 5% of requested baudrate. xbee_ser_open(), xbee_ser_close(), xbee_ser_break()
int xbee_ser_open(xbee_serial_t *serial, uint32_t baudrate)
Opens the serial port connected to XBee serial port serial at baudrate bits/second.
serial XBee serial port baudrate Bits per second of serial data transfer speed. 0 Opened serial port within 5% of requested baudrate. -EINVAL serial is not a valid XBee serial port. -EIO Can't open serial port within 5% of requested baudrate. xbee_ser_baudrate(), xbee_ser_close(), xbee_ser_break()
Referenced by xbee_dev_init.
int xbee_ser_close(xbee_serial_t *serial)
Close the serial port attached to XBee serial port serial.
serial XBee serial port 0 closed serial port -EINVAL serial is not a valid XBee serial port. xbee_ser_open(), xbee_ser_baudrate(), xbee_ser_break()
int xbee_ser_break(xbee_serial_t *serial, int enabled)
Disable the serial transmit pin and pull it low to send a break to the XBee serial port.
serial XBee serial port enabled Set to 1 to start the break or 0 to end the break (and resume transmitting). 0 Success -EINVAL serial is not a valid XBee serial port. xbee_ser_open(), xbee_ser_close()
int xbee_ser_flowcontrol(xbee_serial_t *serial, int enabled)
Enable or disable hardware flow control (CTS/RTS) on the serial port for XBee serial port serial.
serial XBee serial port enabled Set to 0 to disable flow control or non-zero to enable flow control. 0 Success -EINVAL serial is not a valid XBee serial port. xbee_ser_set_rts(), xbee_ser_get_cts()
Referenced by xbee_dev_init.
int xbee_ser_set_rts(xbee_serial_t *serial, int asserted)
Disable hardware flow control and manually set the RTS (ready to send) pin on the XBee device's serial port.
Typically used to enter the XBee device's boot loader and initiate a firmware update. serial XBee serial port asserted Set to 1 to assert RTS (ok for XBee to send to us) or 0 to deassert RTS (tell XBee not to send to us). 0 Success -EINVAL serial is not a valid XBee serial port. xbee_ser_flowcontrol(), xbee_ser_get_cts()
int xbee_ser_get_cts(xbee_serial_t *serial)
Read the status of the /CTS (clear to send) pin on the serial port connected to XBee serial port serial.
Note that this function doesn't return the value of the pin it returns whether it's asserted (i.e., clear to send to the XBee serial port) or not. serial XBee serial port 1 it's clear to send 0 it's not clear to send -EINVAL serial is not a valid XBee serial port. xbee_ser_flowcontrol(), xbee_ser_set_rts()