xbee_discovery.c
int xbee_disc_nd_parse(xbee_node_id_t FAR *parsed, const void FAR *source, int source_length)
Parse a Node Discovery response and store it in an xbee_node_id_t structure.
parsed buffer to hold parsed Node ID message source source of Node ID message, starting with the 16-bit network address source_length number of bytes in source of Node ID message 0 Node ID message parsed and stored in /a parsed -EINVAL invalid parameter passed to function -EBADMSG error parsing Node ID message
References be16toh, EBADMSG, EINVAL, FAR, node_info, XBEE_DISC_MAX_NODEID_LEN.
Referenced by _xbee_disc_parse_and_pass.
const char * xbee_disc_device_type_str(uint8_t device_type)
Return a string ("Coord", "Router", "EndDev", or "???") description for the "Device Type" field of a Node ID message.
device_type the device_type field from a Node ID message pointer to a string describing the type, or "???" if device_type is invalid xbee_node_id_t
Referenced by xbee_disc_node_id_dump.
void xbee_disc_node_id_dump(const xbee_node_id_t FAR *ni)
Debugging function used to dump an xbee_node_id_t structure to stdout.
ni pointer to an xbee_node_id_t structure
References be32toh, PRIsFAR, PRIx32, xbee_disc_device_type_str.
int xbee_disc_add_node_id_handler(xbee_dev_t *xbee, xbee_disc_node_id_fn fn)
Designate a function to receive parsed Node ID messages on a given XBee device.
xbee XBee device to monitor fn function to receive parsed Node ID messages 0 function assigned -EINVAL invalid parameter passed to function -ENOSPC can't assign handler to device xbee_disc_remove_node_id_handler
References EINVAL, ENOSPC, xbee_dev_t::node_id_handler.
int xbee_disc_remove_node_id_handler(xbee_dev_t *xbee, xbee_disc_node_id_fn fn)
Remove a function registered to receive parsed Node ID messages on a given XBee device.
xbee XBee device to monitor fn function to receive parsed Node ID messages 0 function removed -EINVAL invalid parameter passed to function -ENOENT function isn't assigned to this XBee module xbee_disc_remove_node_id_handler
References _xbee_disc_parse_and_pass, EINVAL, ENOENT, FAR, length, node_data, xbee_dev_t::node_id_handler.
int _xbee_disc_parse_and_pass(xbee_dev_t *xbee, const void FAR *node_data, int length)
Common function used to parse Node ID messages from various sources, and then pass them on to registered receivers.
xbee XBee device that received the message node_data pointer to raw Node ID message length length of Node ID message 0 Node ID message parsed and passed on to any registered receivers -EINVAL invalid parameter passed to function -EBADMSG error parsing Node ID message xbee_disc_nd_parse, xbee_disc_add_node_id_handler, xbee_disc_remove_node_id_handler
References xbee_dev_t::node_id_handler, xbee_disc_nd_parse.
Referenced by xbee_disc_nodeid_cluster_handler, xbee_disc_nodeid_frame_handler, xbee_disc_remove_node_id_handler.
int xbee_disc_nodeid_cluster_handler(const wpan_envelope_t FAR *envelope, void FAR *context)
Process messages sent to the Node ID Message cluster (0x0095) of the Digi Data endpoint (0xE8) when ATAO != 0.
This function parses the frame and then passes an xbee_node_id_t structure on to Node ID handlers configured with xbee_disc_add_node_id_handler().Do not call this function directly, it should be included in the Cluster table of the Digi Data endpoint by using the macro XBEE_DISC_DIGI_DATA_CLUSTER_ENTRY.Hosts communicating to XBee modules running with ATAO set to zero do not need to use this handler.See the function help for wpan_aps_handler_fn() for full documentation on this function's API.XBEE_DISC_DIGI_DATA_CLUSTER_ENTRY, xbee_disc_nodeid_frame_handler, xbee_disc_atnd_response_handler
References _xbee_disc_parse_and_pass, EINVAL, XBEE_UNUSED_PARAMETER.
int xbee_disc_atnd_response_handler(xbee_dev_t *xbee, const void FAR *raw, uint16_t length, void FAR *context)
Process AT Command Response frames (type 0x88), looking for ATND responses to parse and pass to Node ID handlers.
This function parses the frame and then passes an xbee_node_id_t structure on to Node ID handlers configured with xbee_disc_add_node_id_handler(). If the ATND command fails or returns a timeout, it passes a NULL xbee_node_id_t to the functions.Do not call this function directly, it should be included in the XBee Frame Handlers table by using the macro XBEE_FRAME_HANDLE_ATND_RESPONSE.See the function help for xbee_frame_handler_fn() for full documentation on this function's API.XBEE_FRAME_HANDLE_ATND_RESPONSE, xbee_disc_nodeid_frame_handler, xbee_disc_nodeid_cluster_handler
int xbee_disc_nodeid_frame_handler(xbee_dev_t *xbee, const void FAR *raw, uint16_t length, void FAR *context)
Process Node Identification frames (type 0x95), sent when ATAO = 0.
These frames are sent to the host when ATAO is set to 0 and a remote node: Has ATD0 set to 1, and someone presses the commissioning button once.Has ATJN set to 1, and has joined the network. This function parses a the frame and then passes an xbee_node_id_t structure on to Node ID handlers configured with xbee_disc_add_node_id_handler().Do not call this function directly, it should be included in the XBee Frame Handlers table by using the macro XBEE_FRAME_HANDLE_AO0_NODEID. Hosts communicating to XBee modules running with ATAO set to a non-zero value do not need to use this handler.See the function help for xbee_frame_handler_fn() for full documentation on this function's API.xbee_disc_nodeid_cluster_handler, xbee_disc_atnd_response_handler
References _xbee_disc_parse_and_pass, EINVAL, FAR, node_data, XBEE_UNUSED_PARAMETER.
int xbee_disc_discover_nodes(xbee_dev_t *xbee, const char *identifier)
Send an ATND command to the XBee, initiating node discovery for all nodes or a specific node's "node identification" (ATNI) string.
Responses from remote nodes are parsed and then passed on to Node ID handlers configured with xbee_disc_add_node_id_handler(). xbee XBee device to use as the target identifier the ATNI (node identification) string of a device on the network, or NULL to discover all devices 0 command sent -EINVAL an invalid parameter was passed to the function -EBUSY transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal). xbee_disc_add_node_id_handler, xbee_disc_remove_node_id_handler
References EINVAL, xbee_cmd_execute, XBEE_DISC_MAX_NODEID_LEN.