zcl_commissioning.c
const zcl64_t zcl_comm_global_epid
zcl_comm_state_t zcl_comm_state
const zcl_comm_startup_attr_t zcl_comm_startup_attributes
const zcl_attribute_tree_t zcl_comm_startup_attribute_tree[][]
int _zcl_comm_startup_control_set(const zcl_attribute_full_t FAR *attribute, zcl_attribute_write_rec_t *rec)
Limit values of startup_control based on firmware type (e.g., some firmwares can't be ZCL_COMM_STARTUP_COORDINATOR).
attribute should be a pointer to zcl_comm_startup_attributes.startup_control rec value from write request See zcl_attribute_write_fn() for calling convention.
References value.
int zcl_comm_response(const wpan_envelope_t FAR *envelope, uint_fast8_t status)
Send response to a Commissioning Server Cluster request.
References FAR, PACKED_STRUCT, status, wpan_envelope_reply, ZCL_FRAME_SERVER_TO_CLIENT, ZCL_FRAME_DISABLE_DEF_RESP, ZCL_FRAME_TYPE_CLUSTER, wpan_envelope_t::payload, wpan_envelope_t::length, wpan_envelope_send, _zcl_comm_command_build.
int _zcl_comm_command_build(wpan_envelope_t FAR *envelope, zcl_header_nomfg_t *header)
Common function used by zcl_comm_restart_device and zcl_comm_reset_parameters.
Fills in frame_control and sequence of header. Fills in cluster_id and payload of envelope. Fills in source_endpoint and profile_id of envelope if necessary.Caller needs to fill in envelope->length and header->command
Referenced by zcl_comm_reset_parameters, zcl_comm_response, zcl_comm_restart_device.
int _zcl_comm_command_send(wpan_envelope_t FAR *envelope)
Common function used by zcl_comm_restart_device and zcl_comm_reset_parameters.
sends the envelope and then resets the payload and length before returning
References wpan_envelope_send.
int zcl_comm_restart_device(wpan_envelope_t FAR *envelope, const zcl_comm_restart_device_cmd_t *parameters)
Send a "Restart Device" command to the ZCL Commissioning Cluster.
envelope Partial envelope used to send the request. Caller must set dev, ieee_address, network_address, profile_id, source_endpoint, dest_endpoint and (optionally) options. On return, payload and length are cleared, and cluster_id is set to ZCL_CLUST_COMMISSIONING. If source_endpoint is 0, function will search the endpoint table for a Commissioning Client Cluster and set the envelope's source_endpoint and profile_id. parameters Parameters for the Restart Device command or NULL for default settings (save changes and restart without delay/jitter). 0 request sent -EINVAL couldn't find source endpoint in endpoint table, or some other error in parameter passed to function !0 error trying to send request
References _zcl_comm_command_build, PACKED_STRUCT.
int zcl_comm_reset_parameters(wpan_envelope_t FAR *envelope, const zcl_comm_reset_startup_param_t *parameters)
Send a "Reset Startup Parameters" command to the ZCL Commissioning Cluster.
envelope Partial envelope used to send the request. Caller must set dev, ieee_address, network_address, profile_id, source_endpoint, dest_endpoint and (optionally) options. On return, payload and length are cleared, and cluster_id is set to ZCL_CLUST_COMMISSIONING. If source_endpoint is 0, function will search the endpoint table for a Commissioning Client Cluster and set the envelope's source_endpoint and profile_id. parameters Parameters for the Reset Startup Parameters command or NULL for default settings (reset current parameters only). 0 request sent -EINVAL couldn't find source endpoint in endpoint table, or some other error in parameter passed to function !0 error trying to send request
References _zcl_comm_command_build, PACKED_STRUCT.
int rand_range(int range)
bool_t zcl_comm_sas_is_valid(const zcl_comm_state_t FAR *comm)
Partial implementation of a function to validate a Startup Attribute Set before trying to use it.
comm Startup Attribute Set to test. TRUE Startup Attribute Set is valid FALSE Startup Attribute Set is invalid and cannot be used Todoadd more tests to this function
int zcl_comm_clust_handler(const wpan_envelope_t FAR *envelope, void FAR *context)
void zcl_comm_sas_init(zcl_comm_startup_param_t *p)
void zcl_comm_factory_reset(uint16_t ms_delay)
Perform a locally-triggered factory reset to default SAS.
ms_delay initiate reset after ms_delay milliseconds
References zcl_comm_state_t::restart_ms.