zdo.h
ZDO_REQUEST_TYPE_SINGLE
ZDO_REQUEST_TYPE_EXTENDED
ZDO_CAPABILITY_ALTERNATE_PAN
ZDO_CAPABILITY_FULL_FUNCTION
ZDO_CAPABILITY_MAINS_POWER
ZDO_CAPABILITY_RX_ON_IDLE
ZDO_CAPABILITY_RESERVED_1
ZDO_CAPABILITY_RESERVED_2
ZDO_CAPABILITY_SECURITY
ZDO_CAPABILITY_ALLOCATE_ADDR
ZDO_STATUS_SUCCESS
ZDO_STATUS_INV_REQUESTTYPE
ZDO_STATUS_DEVICE_NOT_FOUND
ZDO_STATUS_INVALID_EP
ZDO_STATUS_NOT_ACTIVE
ZDO_STATUS_NOT_SUPPORTED
ZDO_STATUS_TIMEOUT
ZDO_STATUS_NO_MATCH
ZDO_STATUS_NO_ENTRY
ZDO_STATUS_NO_DESCRIPTOR
ZDO_STATUS_INSUFFICIENT_SPACE
ZDO_STATUS_NOT_PERMITTED
ZDO_STATUS_TABLE_FULL
ZDO_STATUS_NOT_AUTHORIZED
ZDO_NODE_DESC_MAC_CAPABILITY_ALT_PAN_COORD
ZDO_NODE_DESC_MAC_CAPABILITY_DEVICE_TYPE
ZDO_NODE_DESC_MAC_CAPABILITY_POWER_SOURCE
ZDO_NODE_DESC_MAC_CAPABILITY_RX_ON_IDLE
ZDO_NODE_DESC_MAC_CAPABILITY_RESERVED_4
ZDO_NODE_DESC_MAC_CAPABILITY_RESERVED_5
ZDO_NODE_DESC_MAC_CAPABILITY_SECURITY
ZDO_NODE_DESC_MAC_CAPABILITY_ALLOCATE_ADDR
ZDO_NODE_DESC_SERVER_MASK_PRIMARY_TRUST
ZDO_NODE_DESC_SERVER_MASK_BACKUP_TRUST
ZDO_NODE_DESC_SERVER_MASK_PRIMARY_BINDING
ZDO_NODE_DESC_SERVER_MASK_BACKUP_BINDING
ZDO_NODE_DESC_SERVER_MASK_PRIMARY_DISCOVERY
ZDO_NODE_DESC_SERVER_MASK_BACKUP_DISCOVERY
ZDO_NODE_DESC_SERVER_MASK_NETWORK_MANAGER
ZDO_POWER_SOURCE_MAINS
ZDO_POWER_SOURCE_RECHARGABLE
ZDO_POWER_SOURCE_DISPOSABLE
ZDO_POWER_SOURCE_RESERVED
ZDO_POWER0_SYNC
ZDO_POWER0_PERIODIC
ZDO_POWER0_STIMULATED
ZDO_POWER0_AVAIL_MAINS
ZDO_POWER0_AVAIL_RECHARGABLE
ZDO_POWER0_AVAIL_DISPOSABLE
ZDO_POWER0_AVAIL_RESERVED
ZDO_POWER1_LEVEL_CRITICAL
ZDO_POWER1_LEVEL_33
ZDO_POWER1_LEVEL_66
ZDO_POWER1_LEVEL_FULL
ZDO_POWER1_CURRENT_MAINS
ZDO_POWER1_CURRENT_RECHARGABLE
ZDO_POWER1_CURRENT_DISPOSABLE
ZDO_POWER1_CURRENT_RESERVED
ZDO_CONVERSATION_TIMEOUT
number of seconds to wait for ZDO responses before timing out
Referenced by zdo_simple_desc_request, zdo_send_bind_req, zdo_send_descriptor_req, zdo_send_nwk_addr_req, zdo_send_ieee_addr_req.
ZDO_ENDPOINT
Macro for ZDO endpoint table entry.
state is the name of a wpan_ep_state_t global used to track the ZDO endpoint's state. Can't just have the state declared in zigbee_zdo.c since a device with multiple XBee modules, will need multiple ZDO wpan_ep_state_t globals.
ZDO_CLUST_RESPONSE_MASK
Cluster IDs with the high bit set are responses.
ZDO_CLUST_IS_RESPONSE
ZDO_NWK_ADDR_REQ
cluster ID for ZDO NWK_addr request
Referenced by zdo_send_nwk_addr_req.
ZDO_NWK_ADDR_RSP
cluster ID for ZDO NWK_addr response
ZDO_NET_ADDR_PENDING
ZDO_NET_ADDR_TIMEOUT
ZDO_NET_ADDR_ERROR
ZDO_IEEE_ADDR_REQ
cluster ID for ZDO IEEE_addr request
Referenced by zdo_send_ieee_addr_req.
ZDO_IEEE_ADDR_RSP
cluster ID for ZDO IEEE_addr response
ZDO_IEEE_ADDR_PENDING
ZDO_IEEE_ADDR_TIMEOUT
ZDO_IEEE_ADDR_ERROR
ZDO_NODE_DESC_REQ
cluster ID for ZDO Node_Desc request
ZDO_NODE_DESC_RSP
cluster ID for ZDO Node_Desc response
ZDO_NODE_DESC_FLAGS0_TYPE_MASK
ZDO_NODE_DESC_FLAGS0_TYPE_COORD
ZDO_NODE_DESC_FLAGS0_TYPE_ROUTER
ZDO_NODE_DESC_FLAGS0_TYPE_ENDDEV
ZDO_NODE_DESC_FLAGS0_COMPLEX_DESC_AVAIL
ZDO_NODE_DESC_FLAGS0_USER_DESC_AVAIL
ZDO_NODE_DESC_FLAGS0_RESERVED
ZDO_NODE_DESC_FLAGS1_APS_FIELD
ZDO_NODE_DESC_FLAGS1_FREQUENCY_MASK
ZDO_NODE_DESC_FLAGS1_FREQ_868
ZDO_NODE_DESC_FLAGS1_FREQ_RESERVED_1
ZDO_NODE_DESC_FLAGS1_FREQ_900
ZDO_NODE_DESC_FLAGS1_FREQ_2400
ZDO_NODE_DESC_FLAGS1_FREQ_RESERVED_4
ZDO_POWER_DESC_REQ
cluster ID for ZDO Power_Desc request
ZDO_POWER_DESC_RSP
cluster ID for ZDO Power_Desc response
ZDO_SIMPLE_DESC_REQ
cluster ID for ZDO Simple_Desc request
Referenced by zdo_simple_desc_request.
ZDO_SIMPLE_DESC_RSP
cluster ID for ZDO Simple_Desc response
ZDO_ACTIVE_EP_REQ
cluster ID for ZDO Active_EP request
ZDO_ACTIVE_EP_RSP
cluster ID for ZDO Active_EP response
ZDO_MATCH_DESC_REQ
cluster ID for ZDO Match_Desc request
Referenced by zdo_send_match_desc.
ZDO_MATCH_DESC_RSP
cluster ID for ZDO Match_Desc response
ZDO_COMPLEX_DESC_REQ
cluster ID for ZDO Complex_Desc request
ZDO_COMPLEX_DESC_RSP
cluster ID for ZDO Complex_Desc response
ZDO_USER_DESC_REQ
cluster ID for ZDO User_Desc request
ZDO_USER_DESC_RSP
cluster ID for ZDO User_Desc response
ZDO_DEVICE_ANNCE
cluster ID for ZDO Device_annce announcement
ZDO_DEVICE_ANNCE_CLUSTER
Entry for Device Annce handler in cluster table of ZDO endpoint.
ZDO_BIND_REQ
cluster ID for ZDO Bind request
Referenced by zdo_send_bind_req.
ZDO_BIND_RSP
cluster ID for ZDO Bind response
ZDO_UNBIND_REQ
cluster ID for ZDO Unbind request
Referenced by zdo_send_bind_req.
ZDO_UNBIND_RSP
cluster ID for ZDO Unbind response
ZDO_BIND_DST_MODE_GROUP
zdo_bind_req_t contains 16-bit group address
ZDO_BIND_DST_MODE_ADDR
zdo_bind_req_t contains 64-bit destination address and endpoint
ZDO_MGMT_LEAVE_REQ
cluster ID for ZDO Management Leave Request
ZDO_MGMT_LEAVE_RSP
cluster ID for ZDO Management Leave Response
ZDO_MGMT_LEAVE_REQ_FLAG_NONE
ZDO_MGMT_LEAVE_REQ_FLAG_REJOIN
ZDO_MGMT_LEAVE_REQ_FLAG_REMOVE_CHILDREN
ZDO_MGMT_LEAVE_REQ_ENCRYPTED
extra sending option for zdo_mgmt_leave_req
zdo_nwk_addr_req_t
frame format for ZDO NKW_addr request
zdo_nwk_addr_rsp_header_t
zdo_ieee_addr_req_t
frame format for ZDO IEEE_addr request
typedef zdo_nwk_addr_rsp_header_t zdo_ieee_addr_rsp_header_t
zdo_node_desc_req_t
frame format for ZDO Node_Desc request
zdo_send_descriptor_req()
zdo_node_desc_t
frame format for ZDO Node_Desc response
zdo_node_desc_resp_t
see ZDO_STATUS_* macros
zdo_power_desc_req_t
frame format for ZDO Power_Desc request
zdo_send_descriptor_req()
zdo_power_desc_t
format for ZDO PowerDescriptor
combination of ZDO_POWER0_* macros
zdo_power_desc_rsp_t
frame format for ZDO Power_Desc response
see ZDO_STATUS_* macros
zdo_simple_desc_req_t
frame format for ZDO Simple_Desc request
zdo_simple_desc_resp_header_t
header for ZDO Simple_Desc response, followed by a SimpleDescriptor
see ZDO_STATUS_* macros
zdo_simple_desc_header_t
header for ZDO SimpleDescriptor (part of a Simple_Desc response), followed by uint8_t input cluster count, multiple uint16_t input cluster IDs, uint8_t output cluster count, multiple uint16_t output cluster IDs
0x01 to 0xFE
zdo_active_ep_req_t
frame format for ZDO Active_EP request
zdo_send_descriptor_req()
zdo_active_ep_rsp_header_t
header for ZDO Active_EP response, followed by .ep_count uint8_t endpoints
see ZDO_STATUS_* macros
zdo_match_desc_req_t
header for ZDO Match_Desc request
zdo_match_desc_out_clust_t
Second half of Match_Desc request.
cast to address of zdo_match_desc_req_t offsetof .in_cluster_list + 2 * .num_in_clusters
zdo_match_desc_rsp_header_t
header for ZDO Match_Desc response, followed by .match_length uint8_t endpoints
see ZDO_STATUS_* macros
zdo_complex_desc_req_t
frame format for ZDO Complex_Desc request
zdo_send_descriptor_req()
zdo_user_desc_req_t
frame format for ZDO Complex_Desc request
zdo_send_descriptor_req()
zdo_device_annce_t
frame format for a ZDO Device_annce announcement
zdo_bind_req_header_t
zdo_bind_group_req_t
frame format for a ZDO Bind Request with a group address as the destination (header.dst_addr_mode == ZDO_BIND_DST_MODE_GROUP)
zdo_bind_address_req_t
frame format for a ZDO Bind Request with an IEEE address and endpoint as the destination (header.dst_addr_mode == ZDO_BIND_DST_MODE_ADDR)
zdo_mgmt_leave_req_t
frame format for a ZDO Management Leave Request
zdo_mgmt_leave_rsp_t
addr64 ieee_address_le
uint8_t request_type
See ZDO_REQUEST_TYPE_* macros.
uint8_t start_index
addr64 ieee_remote_le
uint16_t net_remote_le
uint8_t num_assoc_dev
uint16_t network_addr_le
device's network address (little-endian)
Referenced by zdo_match_desc_request, zdo_send_descriptor_req.
uint8_t flags1
uint8_t mac_capability
uint16_t manufacturer_le
uint8_t max_buffer
uint16_t max_incoming_le
uint16_t server_mask_le
uint16_t max_outgoing_le
uint8_t desc_capability
zdo_node_desc_t node_desc
uint8_t power1
combination of ZDO_POWER1_* macros
zdo_power_desc_t power_desc
uint8_t endpoint
0x01 to 0xFE
Referenced by _zcl_send_read_from_zdo_match, zdo_simple_desc_request.
uint8_t length
length of simple descriptor
Referenced by xbee_ser_write, _xbee_checksum_inline, xbee_cmd_set_param_str, _xbee_frame_load, xbee_disc_remove_node_id_handler, xbee_fw_buffer_init, zcl_decode_attribute, _zcl_write_attributes, zcl_command_dump.
uint16_t profile_id_le
endpoint's profile ID (little-endian)
Referenced by zdo_match_desc_request.
uint16_t device_id_le
endpoint's device ID (little-endian)
uint8_t device_version
upper 4 bits are reserved
uint8_t ep_count
uint8_t num_in_clusters
uint16_t in_cluster_list[1][1]
variable length
uint16_t out_cluster_list[1][1]
variable length
uint8_t match_length
uint8_t capability
see ZDO_CAPABILITY_* macros
uint8_t src_endpoint
uint16_t cluster_id_le
uint8_t dst_addr_mode
uint16_t group_addr_le
addr64 dst_address_le
uint8_t dst_endpoint
uint8_t flags
wpan_ep_state_t FAR * zdo_endpoint_state(wpan_dev_t *dev)
Returns the ZDO endpoint's state if a device has a ZDO endpoint.
dev device to query NULL dev does not have a ZDO endpoint !NULL address of wpan_ep_state variable used for state tracking
References _zdo_endpoint_of, _zdo_envelope_create, wpan_endpoint_table_entry_t::ep_state.
Referenced by zdo_send_bind_req, zdo_send_descriptor_req, zdo_send_ieee_addr_req, zdo_send_nwk_addr_req, zdo_simple_desc_request.
int zdo_handler(const wpan_envelope_t FAR *envelope, wpan_ep_state_t FAR *ep_state)
Process ZDO frames (received on endpoint 0 with Profile ID 0).
envelope envelope of received ZDO frame, contains address, endpoint, profile, and cluster info ep_state pointer to endpoint's state structure (used for tracking transactions) 0 successfully processed !0 error trying to process frame
References EINVAL, FAR.
int zdo_send_response(const wpan_envelope_t FAR *request, const void FAR *response, uint16_t length)
Send a response to a ZDO request.
Automatically builds the response envelope and sets its cluster ID (to the request's cluster ID with the high bit set) before sending. request envelope of original request response frame to send in response length length of response 0 sent response !0 error sending response
References wpan_envelope_reply.
int zdo_match_desc_request(void *buffer, int16_t buflen, uint16_t addr_of_interest, uint16_t profile_id, const uint16_t *inClust, const uint16_t *outClust)
Generate a Match_Desc (Match Descriptor) request (ZigBee spec 2.4.3.1.7) to send on the network.
Note that the first byte of buffer is NOT set, and that the caller should set it to the next sequence number/transaction ID. buffer Buffer to hold generated request. buflen Size of buffer used to hold generated request. addr_of_interest See ZDO documentation for NWKAddrOfInterest. profile_id Profile ID to match, must be an actual profile ID (cannot be WPAN_APS_PROFILE_ANY). inClust List of input clusters, ending with WPAN_CLUSTER_END_OF_LIST. Can use NULL if there aren't any input clusters. outClust List of output clusters, ending with WPAN_CLUSTER_END_OF_LIST. Can use NULL if there aren't any output clusters. -ENOSPC buffer isn't large enough to hold request; need 7 bytes plus (2 * the number of clusters) >0 number of bytes written to buffer
References _match_desc_cluster_list, _zdo_match_desc_respond, EINVAL, ENOSPC, FAR, htole16, network_addr_le, PACKED_STRUCT, profile_id_le.
Referenced by zdo_send_match_desc.
int zdo_send_nwk_addr_req(wpan_dev_t *dev, const addr64 FAR *ieee_be, uint16_t FAR *net)
Given a device's IEEE (64-bit) address, get its 16-bit network address by unicasting a ZDO NWK_addr request to it.
After calling this function, *net is set to ZDO_NET_ADDR_PENDING.When a SUCCESS response comes back, *net is set to the 16-bit network address in the response.When an ERROR response comes back, *net is set to ZDO_NET_ADDR_ERROR.If a timeout occurs waiting for a response, *net is set to ZDO_NET_ADDR_TIMEOUT.(So the caller needs to wait until (*net != ZDO_NET_ADDR_PENDING)). dev wpan_dev_t to send request ieee_be IEEE address (in big-endian byte order) of device we're seeking a network address for net location to store the 16-bit network address when the NWK_addr response comes back. -EINVAL invalid parameter passed to function -ENOSPC conversation table is full, wait and try sending later 0 request sent !0 error trying to send request
References _zdo_envelope_create, _zdo_process_nwk_addr_resp, ADDR64_STRING_LENGTH, wpan_envelope_t::cluster_id, EINVAL, wpan_envelope_t::length, memcpy_betole, wpan_envelope_t::payload, wpan_conversation_register, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state, ZDO_NWK_ADDR_REQ.
int zdo_send_ieee_addr_req(wpan_dev_t *dev, uint16_t net_addr, addr64 FAR *ieee_be)
Given a device's 16-bit network address, get its IEEE (64-bit) address by unicasting a ZDO IEEE_addr request to it.
This function only works with the following XBee firmware versions: S2C: 401F and later (ZigBee), 5123 and later (Smart Energy)S2[B]: not supported After calling this function, *ieee_be is set to *ZDO_IEEE_ADDR_PENDING.When a SUCCESS response comes back, *ieee_be is set to the 64-bit IEEE address in the response.If an ERROR response comes back, *ieee_be is set to all zeros (*ZDO_IEEE_ADDR_ERROR).If a timeout occurs waiting for a response, *ieee_be is set to ZDO_IEEE_ADDR_TIMEOUT.addr64ieee_be;//IEEEaddressinbig-endianbyteorder uint16_tnet_addr; printf("SendingIEEE_addrrequestfor0x%04X\n",net_addr); zdo_send_ieee_addr_req(dev,net_addr,&ieee_be); do{ wpan_tick(dev); }while(addr64_equal(&ieee_be,ZDO_IEEE_ADDR_PENDING)); if(addr64_equal(&ieee_be,ZDO_IEEE_ADDR_TIMEOUT)) { printf("IEEE_addrrequestfor0x%04Xtimedout\n",net_addr); } elseif(addr64_is_zero(&ieee_be)) { printf("ErrorretrievingIEEE_addrfor0x%04X\n",net_addr); } else { printf("IEEEaddressof0x%04Xis%"PRIsFAR"\n",net_addr, addr64_format(buffer,&ieee_be)); } dev wpan_dev_t to send request net_addr network address of device we're seeking an IEEE address for ieee_be location to store the 64-bit IEEE address when the IEEE_addr response comes back. -EINVAL invalid parameter passed to function -ENOSPC conversation table is full, wait and try sending later 0 request sent !0 error trying to send request
References _zdo_process_ieee_addr_resp, wpan_envelope_t::cluster_id, EINVAL, htole16, wpan_envelope_t::length, wpan_envelope_t::payload, wpan_conversation_register, wpan_envelope_create, WPAN_IEEE_ADDR_UNDEFINED, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state, ZDO_IEEE_ADDR_REQ.
int zdo_simple_desc_request(wpan_envelope_t *envelope, uint16_t addr_of_interest, uint_fast8_t endpoint, wpan_response_fn callback, const void FAR *context)
Send a ZDO Simple Descriptor Request.
The simple descriptor contains information specific to each of a node's endpoints. Use the ZDO Simple Descriptor Request to get a descriptor for an endpoint on a remote node. envelope Envelope created with wpan_envelope_create(). Only dev, ieee_address and network_address should be set, all other structure elements should be zero. Address may match addr_of_interest or an alternative device that contains the discovery information of that device (like an end device's parent). addr_of_interest Network address of the device for which the simple descriptor is required. endpoint Endpoint of interest, a value from 1 to 254. callback Function to receive the Simple Descriptor Response. See documentation for wpan_response_fn for this callback's API. context Context pointer passed to the callback along with the response. 0 request sent !0 error sending request
References _zdo_simple_desc_respond, wpan_envelope_t::cluster_id, wpan_envelope_t::dest_endpoint, wpan_envelope_t::dev, EINVAL, endpoint, FAR, htole16, wpan_envelope_t::length, wpan_envelope_t::payload, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, wpan_conversation_register, WPAN_ENDPOINT_ZDO, wpan_envelope_send, WPAN_PROFILE_ZDO, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state, ZDO_SIMPLE_DESC_REQ.
int zdo_send_bind_req(wpan_envelope_t *envelope, uint16_t type, wpan_response_fn callback, void FAR *context)
Send a ZDO Bind (or Unbind) Request to the destination address in the envelope.
Binds .dest_endpoint on .ieee_address to .source_endpoint on .dev using .cluster_id.Ignores the .options, .payload, and .length members of the envelope. envelope addressing information used for the Bind Request type ZDO_BIND_REQ for a Bind Request or ZDO_UNBIND_REQ for an Unbind Request; all other values are invalid callback callback to receive Bind/Unbind (or Default) Response; NULL if you don't care about the response context context passed to callback 0 successfully sent request -EINVAL bad parameter passed to function !0 error sending request
References _zdo_envelope_create, wpan_envelope_t::cluster_id, wpan_envelope_t::dev, EINVAL, wpan_envelope_t::ieee_address, wpan_envelope_t::length, wpan_envelope_t::network_address, PACKED_STRUCT, wpan_envelope_t::payload, type, wpan_conversation_register, ZDO_BIND_REQ, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state, ZDO_UNBIND_REQ.
int zdo_mgmt_leave_req(wpan_dev_t *dev, const addr64 *address, uint16_t flags)
Send a ZDO Management Leave Request.
dev device to send request on address address to send request to, or NULL for self-addressed flags one or more of the following flags: ZDO_MGMT_LEAVE_REQ_FLAG_NONEZDO_MGMT_LEAVE_REQ_FLAG_REMOVE_CHILDREN - set the Remove Children flag in the ZDO requestZDO_MGMT_LEAVE_REQ_FLAG_REJOIN - set the Rejoin flag in the ZDO requestZDO_MGMT_LEAVE_REQ_ENCRYPTED - send the request with APS encryption 0 successfully sent request -EINVAL bad parameter passed to function !0 error sending request
int zdo_send_descriptor_req(wpan_envelope_t *envelope, uint16_t cluster, uint16_t addr_of_interest, wpan_response_fn callback, const void FAR *context)
Send a ZDO Node, Power, Complex or User Descriptor request, or an Active Endpoint request.
envelope Envelope created by wpan_envelope_create; this function will fill in the cluster and reset the payload and length. cluster Any ZDO request with a transaction and 16-bit network address as its only fields, including: ZDO_NODE_DESC_REQZDO_POWER_DESC_REQZDO_ACTIVE_EP_REQZDO_COMPLEX_DESC_REQZDO_USER_DESC_REQ addr_of_interest address to use in ZDO request callback function to receive response context context to pass to callback with response !0 error sending request 0 request sent
References wpan_envelope_t::cluster_id, wpan_envelope_t::dest_endpoint, wpan_envelope_t::dev, EINVAL, htole16, wpan_envelope_t::length, network_addr_le, PACKED_STRUCT, wpan_envelope_t::payload, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, wpan_conversation_register, WPAN_ENDPOINT_ZDO, wpan_envelope_send, WPAN_PROFILE_ZDO, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state.