zigbee_zdo.c
zigbee_zdo_debug
ZDO_MAX_ENDPOINTS
MAX_CLUSTERS
zigbee_zdo_debug const wpan_endpoint_table_entry_t * _zdo_endpoint_of(wpan_dev_t *dev)
Return the endpoint table entry for the ZDO endpoint.
dev search the endpoint table of this device NULL couldn't find the ZDO endpoint for dev !NULL pointer to the ZDO endpoint of dev
References wpan_endpoint_match, WPAN_ENDPOINT_ZDO, WPAN_PROFILE_ZDO.
Referenced by zdo_endpoint_state.
wpan_ep_state_t FAR * zdo_endpoint_state(wpan_dev_t *dev)
Returns the ZDO endpoint's state if a device has a ZDO endpoint.
dev device to query NULL dev does not have a ZDO endpoint !NULL address of wpan_ep_state variable used for state tracking
References _zdo_endpoint_of, _zdo_envelope_create, wpan_endpoint_table_entry_t::ep_state.
Referenced by zdo_send_bind_req, zdo_send_descriptor_req, zdo_send_ieee_addr_req, zdo_send_nwk_addr_req, zdo_simple_desc_request.
zigbee_zdo_debug const addr64 * _zdo_envelope_create(wpan_envelope_t *envelope, wpan_dev_t *dev, const addr64 *address)
helper function for creating ZDO request envelopes
envelope envelope to populate dev device that will send this envelope address send request to the given target, or NULL for a self-addressed request either address or a pointer to an all-zero IEEE address return value may change to something more useful in a future release
References wpan_dev_t::address, wpan_envelope_t::dest_endpoint, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, WPAN_ENDPOINT_ZDO, wpan_envelope_create, WPAN_IEEE_ADDR_ALL_ZEROS, WPAN_NET_ADDR_UNDEFINED, WPAN_PROFILE_ZDO.
Referenced by zdo_endpoint_state, zdo_send_bind_req, zdo_send_nwk_addr_req.
int zdo_send_response(const wpan_envelope_t FAR *request, const void FAR *response, uint16_t length)
Send a response to a ZDO request.
Automatically builds the response envelope and sets its cluster ID (to the request's cluster ID with the high bit set) before sending. request envelope of original request response frame to send in response length length of response 0 sent response !0 error sending response
References wpan_envelope_reply.
int _match_desc_cluster_list(uint8_t **buffer, const uint16_t *clust_read, int max_count)
Writes to *buffer, an 8-bit cluster count followed by the 16-bit cluster IDs in little-endian byte order. buffer location to store cluster list, updated to point to first byte after bytes written cluster_read list of 16-bit cluster IDs, terminated by WPAN_CLUSTER_END_OF_LIST max_count maximum number of clusters to write to *buffer -ENOSPC can't fit list of clusters into buffer >=0 number of clusters written to buffer
References ENOSPC, htole16, WPAN_CLUSTER_END_OF_LIST.
Referenced by zdo_match_desc_request.
int zdo_match_desc_request(void *buffer, int16_t buflen, uint16_t addr_of_interest, uint16_t profile_id, const uint16_t *inClust, const uint16_t *outClust)
Generate a Match_Desc (Match Descriptor) request (ZigBee spec 2.4.3.1.7) to send on the network.
Note that the first byte of buffer is NOT set, and that the caller should set it to the next sequence number/transaction ID. buffer Buffer to hold generated request. buflen Size of buffer used to hold generated request. addr_of_interest See ZDO documentation for NWKAddrOfInterest. profile_id Profile ID to match, must be an actual profile ID (cannot be WPAN_APS_PROFILE_ANY). inClust List of input clusters, ending with WPAN_CLUSTER_END_OF_LIST. Can use NULL if there aren't any input clusters. outClust List of output clusters, ending with WPAN_CLUSTER_END_OF_LIST. Can use NULL if there aren't any output clusters. -ENOSPC buffer isn't large enough to hold request; need 7 bytes plus (2 * the number of clusters) >0 number of bytes written to buffer
References _match_desc_cluster_list, _zdo_match_desc_respond, EINVAL, ENOSPC, FAR, htole16, network_addr_le, PACKED_STRUCT, profile_id_le.
Referenced by zdo_send_match_desc.
zigbee_zdo_debug int _zdo_match_desc_respond(const wpan_envelope_t FAR *envelope)
Respond to a Match Descriptor (Match_Desc) request (ZigBee spec 2.4.3.1.7).
This ZDO request is used to find endpoints using a particular Profile ID and a cluster from a list of input and output clusters. envelope envelope of request 0 successfully sent response, or none of the endpoints matched the request -ENODATA don't know network address of envelope->dev !0 error parsing request or sending response
References FAR, PACKED_STRUCT, type.
Referenced by zdo_match_desc_request.
int zdo_simple_desc_request(wpan_envelope_t *envelope, uint16_t addr_of_interest, uint_fast8_t endpoint, wpan_response_fn callback, const void FAR *context)
Send a ZDO Simple Descriptor Request.
The simple descriptor contains information specific to each of a node's endpoints. Use the ZDO Simple Descriptor Request to get a descriptor for an endpoint on a remote node. envelope Envelope created with wpan_envelope_create(). Only dev, ieee_address and network_address should be set, all other structure elements should be zero. Address may match addr_of_interest or an alternative device that contains the discovery information of that device (like an end device's parent). addr_of_interest Network address of the device for which the simple descriptor is required. endpoint Endpoint of interest, a value from 1 to 254. callback Function to receive the Simple Descriptor Response. See documentation for wpan_response_fn for this callback's API. context Context pointer passed to the callback along with the response. 0 request sent !0 error sending request
References _zdo_simple_desc_respond, wpan_envelope_t::cluster_id, wpan_envelope_t::dest_endpoint, wpan_envelope_t::dev, EINVAL, endpoint, FAR, htole16, wpan_envelope_t::length, wpan_envelope_t::payload, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, wpan_conversation_register, WPAN_ENDPOINT_ZDO, wpan_envelope_send, WPAN_PROFILE_ZDO, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state, ZDO_SIMPLE_DESC_REQ.
zigbee_zdo_debug int _zdo_simple_desc_respond(const wpan_envelope_t FAR *envelope)
Respond to a Simple Descriptor (Simple_Desc) request (ZigBee spec 2.4.3.1.5).
This ZDO request is used to get information about a single endpoint. envelope envelope of request 0 successfully sent response -ENODATA don't know network address of envelope->dev !0 error parsing request or sending response
References EINVAL, FAR, PACKED_STRUCT, WPAN_NET_ADDR_UNDEFINED.
Referenced by zdo_simple_desc_request.
int _simple_desc_cluster_list(uint8_t **buffer, int max_count, uint8_t mask, const wpan_cluster_table_entry_t *entry)
Writes to *buffer, an 8-bit cluster count followed by the 16-bit IDs for entries in a cluster table matching a given mask. buffer location to store cluster list, updated to point to first byte after bytes written max_count maximum number of clusters to write to *buffer mask mask used to restrict entries entry list of clusters, terminated by an entry with and ID of WPAN_CLUSTER_END_OF_LIST -ENOSPC can't fit list of clusters into buffer >=0 number of clusters written to buffer
References wpan_cluster_table_entry_t::cluster_id, ENOSPC, wpan_cluster_table_entry_t::flags, htole16, WPAN_CLUSTER_END_OF_LIST.
zigbee_zdo_debug int _zdo_active_ep_respond(const wpan_envelope_t FAR *envelope)
Respond to an Active Endpoint (Active_EP) request (ZigBee spec 2.4.3.1.6).
This ZDO request is used to get a list of active endoints on a device. envelope envelope of request 0 successfully sent response -ENODATA don't know network address of envelope->dev !0 error parsing request or sending response
References PACKED_STRUCT.
int zdo_handler(const wpan_envelope_t FAR *envelope, wpan_ep_state_t FAR *ep_state)
Process ZDO frames (received on endpoint 0 with Profile ID 0).
envelope envelope of received ZDO frame, contains address, endpoint, profile, and cluster info ep_state pointer to endpoint's state structure (used for tracking transactions) 0 successfully processed !0 error trying to process frame
References EINVAL, FAR.
int zdo_send_bind_req(wpan_envelope_t *envelope, uint16_t type, wpan_response_fn callback, void FAR *context)
Send a ZDO Bind (or Unbind) Request to the destination address in the envelope.
Binds .dest_endpoint on .ieee_address to .source_endpoint on .dev using .cluster_id.Ignores the .options, .payload, and .length members of the envelope. envelope addressing information used for the Bind Request type ZDO_BIND_REQ for a Bind Request or ZDO_UNBIND_REQ for an Unbind Request; all other values are invalid callback callback to receive Bind/Unbind (or Default) Response; NULL if you don't care about the response context context passed to callback 0 successfully sent request -EINVAL bad parameter passed to function !0 error sending request
References _zdo_envelope_create, wpan_envelope_t::cluster_id, wpan_envelope_t::dev, EINVAL, wpan_envelope_t::ieee_address, wpan_envelope_t::length, wpan_envelope_t::network_address, PACKED_STRUCT, wpan_envelope_t::payload, type, wpan_conversation_register, ZDO_BIND_REQ, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state, ZDO_UNBIND_REQ.
int zdo_mgmt_leave_req(wpan_dev_t *dev, const addr64 *address, uint16_t flags)
Send a ZDO Management Leave Request.
dev device to send request on address address to send request to, or NULL for self-addressed flags one or more of the following flags: ZDO_MGMT_LEAVE_REQ_FLAG_NONEZDO_MGMT_LEAVE_REQ_FLAG_REMOVE_CHILDREN - set the Remove Children flag in the ZDO requestZDO_MGMT_LEAVE_REQ_FLAG_REJOIN - set the Rejoin flag in the ZDO requestZDO_MGMT_LEAVE_REQ_ENCRYPTED - send the request with APS encryption 0 successfully sent request -EINVAL bad parameter passed to function !0 error sending request
int zdo_send_descriptor_req(wpan_envelope_t *envelope, uint16_t cluster, uint16_t addr_of_interest, wpan_response_fn callback, const void FAR *context)
Send a ZDO Node, Power, Complex or User Descriptor request, or an Active Endpoint request.
envelope Envelope created by wpan_envelope_create; this function will fill in the cluster and reset the payload and length. cluster Any ZDO request with a transaction and 16-bit network address as its only fields, including: ZDO_NODE_DESC_REQZDO_POWER_DESC_REQZDO_ACTIVE_EP_REQZDO_COMPLEX_DESC_REQZDO_USER_DESC_REQ addr_of_interest address to use in ZDO request callback function to receive response context context to pass to callback with response !0 error sending request 0 request sent
References wpan_envelope_t::cluster_id, wpan_envelope_t::dest_endpoint, wpan_envelope_t::dev, EINVAL, htole16, wpan_envelope_t::length, network_addr_le, PACKED_STRUCT, wpan_envelope_t::payload, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, wpan_conversation_register, WPAN_ENDPOINT_ZDO, wpan_envelope_send, WPAN_PROFILE_ZDO, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state.
zigbee_zdo_debug int _zdo_process_nwk_addr_resp(wpan_conversation_t FAR *conversation, const wpan_envelope_t FAR *envelope)
Callback function to process NWK_addr response frames.
The context field of the conversation is the location to store the 16-bit address returned in the response.zdo_send_nwk_addr_req()
References FAR, PACKED_STRUCT.
Referenced by zdo_send_nwk_addr_req.
int zdo_send_nwk_addr_req(wpan_dev_t *dev, const addr64 FAR *ieee_be, uint16_t FAR *net)
Given a device's IEEE (64-bit) address, get its 16-bit network address by unicasting a ZDO NWK_addr request to it.
After calling this function, *net is set to ZDO_NET_ADDR_PENDING.When a SUCCESS response comes back, *net is set to the 16-bit network address in the response.When an ERROR response comes back, *net is set to ZDO_NET_ADDR_ERROR.If a timeout occurs waiting for a response, *net is set to ZDO_NET_ADDR_TIMEOUT.(So the caller needs to wait until (*net != ZDO_NET_ADDR_PENDING)). dev wpan_dev_t to send request ieee_be IEEE address (in big-endian byte order) of device we're seeking a network address for net location to store the 16-bit network address when the NWK_addr response comes back. -EINVAL invalid parameter passed to function -ENOSPC conversation table is full, wait and try sending later 0 request sent !0 error trying to send request
References _zdo_envelope_create, _zdo_process_nwk_addr_resp, ADDR64_STRING_LENGTH, wpan_envelope_t::cluster_id, EINVAL, wpan_envelope_t::length, memcpy_betole, wpan_envelope_t::payload, wpan_conversation_register, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state, ZDO_NWK_ADDR_REQ.
zigbee_zdo_debug int _zdo_process_ieee_addr_resp(wpan_conversation_t FAR *conversation, const wpan_envelope_t FAR *envelope)
Callback function to process IEEE_addr response frames.
The context field of the conversation is the location to store the 64-bit address returned in the response.zdo_send_ieee_addr_req()
References ADDR64_STRING_LENGTH, FAR, PACKED_STRUCT.
Referenced by zdo_send_ieee_addr_req.
int zdo_send_ieee_addr_req(wpan_dev_t *dev, uint16_t net_addr, addr64 FAR *ieee_be)
Given a device's 16-bit network address, get its IEEE (64-bit) address by unicasting a ZDO IEEE_addr request to it.
This function only works with the following XBee firmware versions: S2C: 401F and later (ZigBee), 5123 and later (Smart Energy)S2[B]: not supported After calling this function, *ieee_be is set to *ZDO_IEEE_ADDR_PENDING.When a SUCCESS response comes back, *ieee_be is set to the 64-bit IEEE address in the response.If an ERROR response comes back, *ieee_be is set to all zeros (*ZDO_IEEE_ADDR_ERROR).If a timeout occurs waiting for a response, *ieee_be is set to ZDO_IEEE_ADDR_TIMEOUT.addr64ieee_be;//IEEEaddressinbig-endianbyteorder uint16_tnet_addr; printf("SendingIEEE_addrrequestfor0x%04X\n",net_addr); zdo_send_ieee_addr_req(dev,net_addr,&ieee_be); do{ wpan_tick(dev); }while(addr64_equal(&ieee_be,ZDO_IEEE_ADDR_PENDING)); if(addr64_equal(&ieee_be,ZDO_IEEE_ADDR_TIMEOUT)) { printf("IEEE_addrrequestfor0x%04Xtimedout\n",net_addr); } elseif(addr64_is_zero(&ieee_be)) { printf("ErrorretrievingIEEE_addrfor0x%04X\n",net_addr); } else { printf("IEEEaddressof0x%04Xis%"PRIsFAR"\n",net_addr, addr64_format(buffer,&ieee_be)); } dev wpan_dev_t to send request net_addr network address of device we're seeking an IEEE address for ieee_be location to store the 64-bit IEEE address when the IEEE_addr response comes back. -EINVAL invalid parameter passed to function -ENOSPC conversation table is full, wait and try sending later 0 request sent !0 error trying to send request
References _zdo_process_ieee_addr_resp, wpan_envelope_t::cluster_id, EINVAL, htole16, wpan_envelope_t::length, wpan_envelope_t::payload, wpan_conversation_register, wpan_envelope_create, WPAN_IEEE_ADDR_UNDEFINED, ZDO_CONVERSATION_TIMEOUT, zdo_endpoint_state, ZDO_IEEE_ADDR_REQ.