zigbee_zcl.c
zigbee_zcl_debug
ZCL_DISCOVER_ATTRIB_MAX
const zcl_attribute_tree_t FAR zcl_attributes_none[1][1]
If a cluster doesn't have attributes, use zcl_attributes_none (a single, empty attribute list) in the cluster definition.
Don't use NULL, since the APS dispatcher will use endpoint's context if the cluster's context is NULL.
int zcl_send_response(zcl_command_t *request, const void FAR *response, uint16_t length)
Send a response to a ZCL command.
Uses information from the command received to populate fields in the response. request command to respond to response payload to send as response length number of bytes in response 0 successfully sent response !0 error on send
const zcl_attribute_base_t FAR * zcl_attribute_get_next(const zcl_attribute_base_t FAR *entry)
Return a pointer to the next attribute entry from an attribute table.
entry current entry from the table NULL entry was NULL !NULL pointer to next attribute record If entry points to the last entry in the table, this function will return the same address instead of advancing off the end of the table. zcl_find_attribute
References ZCL_ATTRIBUTE_END_OF_LIST.
Referenced by zcl_create_attribute_records.
const zcl_attribute_base_t FAR * zcl_find_attribute(const zcl_attribute_base_t FAR *entry, uint16_t search_id)
Search the attribute table starting at entry, for attribute ID search_id.
entry starting entry for search search_id attribute ID to look for NULL attribute id search_id not in list !NULL pointer to attribute record
int zcl_build_header(zcl_header_response_t *rsp, zcl_command_t *cmd)
Support function to fill in a ZCL response header.
Set the frame_control, sequence and optional mfg_code fields of the ZCL response header, and return the offset to the actual start of the header (non-mfg specific skips the first two bytes). rsp buffer to store header of response cmd command we're responding to 0 responding to manufacturer-specific command 2 responding to non-manufacturer-specific command -EINVAL invalid parameter passed to function
int zcl_default_response(zcl_command_t *request, uint8_t status)
Send a Default Response (ZCL_CMD_DEFAULT_RESP) to a given command.
request command we're responding to status status to use in the response (see ZCL_STATUS_* macros under "ZCL Status Enumerations" in zigbee/zcl.h) 0 successfully sent response, or response not required (message was broadcast, sent to the broadcast endpoint, or sender set the disable default response bit) !0 error on send -EINVAL invalid parameter passed to function
References command, PACKED_STRUCT, status.
Referenced by zcl_invalid_cluster.
int zcl_check_minmax(const zcl_attribute_base_t FAR *entry, const uint8_t FAR *buffer_le)
Checks whether a new value from a Write Attributes command is within the limits specified for a given attribute.
entry entry to use for min/max check buffer_le buffer with new value (in little-endian byte order), from write attributes command 0 new value is within range (or attribute doesn't have a min/max) -EINVAL invalid parameter passed to function !0 value is out of range
References FAR, value.
int zcl_parse_attribute_record(const zcl_attribute_base_t FAR *entry, zcl_attribute_write_rec_t *write_rec)
Parse an attribute record from a Write Attributes Request or a Read Attributes Response and possibly store the new attribute value.
If ZCL_ATTR_WRITE_FLAG_READ_RESP is set in write_rec->flags, write_rec->buffer will be parsed as a Read Attributes Response record. Otherwise, it's parsed as a Write Attributes Request record. entry attribute table to search or NULL if there aren't any attributes on this cluster write_rec state information for parsing write request >=0 number of bytes consumed from buffer -EINVAL invalid parameter passed to function
References FAR, type.
uint32_t zcl_convert_24bit(const void FAR *value_le, bool_t extend_sign)
Convert a 24-bit (3-byte) little-endian value to a 32-bit value in host byte order.
value_le pointer to 3 bytes to convert extend_sign if TRUE, set high byte of result to 0xFF if top bit of 24-bit value is set A 32-bit, host-byte-order version of the 24-bit, little-endian value passed in.
References FAR.
int zcl_decode_attribute(const zcl_attribute_base_t FAR *entry, zcl_attribute_write_rec_t *rec)
Decode attribute value from a Write Attribute Request or Read Attribute Response record and optionally write to entry.
entry entry from attribute table rec state information for parsing write request >=0 number of bytes consumed from rec->buffer -EINVAL invalid parameter passed to function
References FAR, length.
Referenced by _zcl_identify_time_set.
zigbee_zcl_debug int _zcl_write_attributes(zcl_command_t *cmd)
Process the three types of Write Attributes requests.
Handles Write Attributes (ZCL_CMD_WRITE_ATTRIB), Write Attributes Undivided (ZCL_CMD_WRITE_ATTRIB_UNDIV) and Write Attributes No Response (ZCL_CMD_WRITE_ATTRIB_NORESP). cmd command to respond to 0 successfully sent response or "No Response" requested !0 error on send TodoGenerate error if command is not one of the three expected commands.TodoUpdate to limit number of status records in response.
References length, PACKED_STRUCT, status.
zigbee_zcl_debug int _zcl_encode_struct_value(uint8_t FAR *buffer, int16_t bufsize, const zcl_struct_t FAR *zcl_struct)
Format a ZCL struct for a Read Attributes Response or a Write Attributes Request.
buffer buffer to store encoded attribute bufsize number of bytes available in buffer zcl_struct struct to encode into buffer Copies the value of attribute entry to buffer in little-endian byte order. Will not write more than bufsize bytes. Used to build ZCL frames. -ZCL_STATUS_INSUFFICIENT_SPACE buffer too small to encode value -ZCL_STATUS_FAILURE unknown/unsupported attribute type -ZCL_STATUS_HARDWARE_FAILURE failure updating attribute value -ZCL_STATUS_SOFTWARE_FAILURE failure updating attribute value >=0 number of bytes written zcl_encode_attribute_value
References FAR.
zigbee_zcl_debug int _zcl_encode_array_value(uint8_t FAR *buffer, int16_t bufsize, const zcl_array_t FAR *array)
Format a ZCL array for a Read Attributes Response or a Write Attributes Request.
buffer buffer to store encoded attribute bufsize number of bytes available in buffer array array to encode into buffer Copies the value of attribute entry to buffer in little-endian byte order. Will not write more than bufsize bytes. Used to build ZCL frames. -ZCL_STATUS_INSUFFICIENT_SPACE buffer too small to encode value -ZCL_STATUS_FAILURE unknown/unsupported attribute type -ZCL_STATUS_HARDWARE_FAILURE failure updating attribute value -ZCL_STATUS_SOFTWARE_FAILURE failure updating attribute value >=0 number of bytes written zcl_encode_attribute_value
References FAR.
int zcl_encode_attribute_value(uint8_t FAR *buffer, int16_t bufsize, const zcl_attribute_base_t FAR *entry)
Format a ZCL attribute's value for a Read Attributes Response or a Write Attributes Request.
Copies the value of attribute entry to buffer in little-endian byte order. Will not write more than bufsize bytes. Used to build ZCL frames. buffer buffer to store encoded attribute bufsize number of bytes available in buffer entry attribute to encode into buffer -ZCL_STATUS_SOFTWARE_FAILURE invalid parameter passed in -ZCL_STATUS_DEFINED_OUT_OF_BAND ghost attribute with NULL value -ZCL_STATUS_INSUFFICIENT_SPACE buffer too small to encode value -ZCL_STATUS_FAILURE unknown/unsupported attribute type -ZCL_STATUS_HARDWARE_FAILURE failure updating attribute value -ZCL_STATUS_SOFTWARE_FAILURE failure updating attribute value >=0 number of bytes written
References FAR, status, type.
Referenced by zcl_create_attribute_records.
zigbee_zcl_debug int _zcl_read_attributes(zcl_command_t *cmd)
Process the Read Attributes Command (ZCL_CMD_READ_ATTRIB).
cmd command to respond to 0 successfully sent response !0 error on send -EINVAL NULL cmd parameter
References FAR.
zigbee_zcl_debug int _zcl_discover_attributes(zcl_command_t *cmd)
Process the Discover Attributes Command (ZCL_CMD_DISCOVER_ATTRIB).
cmd command to respond to 0 successfully sent response !0 error on send
References FAR, PACKED_STRUCT.
int zcl_command_build(zcl_command_t *cmd, const wpan_envelope_t FAR *envelope, zcl_attribute_tree_t FAR *tree)
Parse a ZCL request and store in a zcl_command_t structure with fields in fixed locations (therefore easier to use than the variable-length frame header).
Also uses the direction bit and manufacturer ID to search the attribute tree for the correct list of attributes. cmd buffer to store parsed ZCL command envelope envelope from received message tree pointer to attribute tree for cluster or NULL if the cluster doesn't have any attributes (typically passed in via endpoint dispatcher) 0 parsed payload from envelope into cmd -EINVAL invalid parameter passed to function -EBADMSG frame is too small for ZCL header's frame_control value
References FAR.
Referenced by _zcl_basic_server, _zcl_onoff_handler, zcl_general_command, zcl_identify_command, zcl_invalid_cluster, zcl_invalid_command, zcl_time_client.
void zcl_command_dump(const zcl_command_t *cmd)
Debugging routine that dumps contents of a parsed ZCL command structure to STDOUT.
cmd zcl_command_t structure populated by zcl_command_build()
References _TABLE_ENTRIES, zcl_command_t::command, FAR, zcl_command_t::frame_control, length, zcl_command_t::length, zcl_command_t::mfg_code, zcl_command_t::sequence, ZCL_CMD_DEFAULT_RESP, ZCL_CMD_WRITE_ATTRIB_RESP, ZCL_FRAME_CLIENT_TO_SERVER, ZCL_FRAME_DIRECTION, ZCL_FRAME_DISABLE_DEF_RESP, ZCL_FRAME_TYPE_MASK, ZCL_FRAME_TYPE_PROFILE, zcl_command_t::zcl_payload, zcl_status_text.
void zcl_envelope_payload_dump(const wpan_envelope_t *envelope)
Debugging routine that parses an envelope payload as a ZCL command and dumps a parsed copy to STDOUT.
envelope wpan_envelope_t structure with a ZCL command payload
int zcl_invalid_cluster(const wpan_envelope_t FAR *envelope, wpan_ep_state_t FAR *ep_state)
Called if a request comes in for an invalid endpoint/cluster combination.
Sends a Default Response (ZCL_CMD_DEFAULT_RESP) of #ZCL_STATUS_FAILURE unless the received command was a Default Response or was broadcast. envelope envelope from received message ep_state pointer to endpoint's wpan_ep_state_t 0 command was a default response (and therefore ignored), or a default response was successfully sent !0 error sending response
References XBEE_UNUSED_PARAMETER, zcl_command_build, zcl_default_response.
int zcl_invalid_command(const wpan_envelope_t FAR *envelope)
Called if a request comes in for an invalid command on a valid endpoint/cluster combination.
Sends a Default Response (ZCL_CMD_DEFAULT_RESP) unless the received command was a Default Response or was broadcast. Depending on the command received, the response will be one of: ZCL_STATUS_UNSUP_CLUSTER_COMMANDZCL_STATUS_UNSUP_GENERAL_COMMANDZCL_STATUS_UNSUP_MANUF_CLUSTER_COMMANDZCL_STATUS_UNSUP_MANUF_GENERAL_COMMAND envelope envelope from received message 0 default response was successfully sent, or command did not require a default response !0 error building or sending response
References zcl_command_t::frame_control, status, zcl_command_build, ZCL_FRAME_MFG_SPECIFIC.
int zcl_general_command(const wpan_envelope_t FAR *envelope, void FAR *context)
Handler for ZCL General Commands.
Used as the handler for attribute-only clusters (e.g., Basic Cluster), or called from a cluster's handler for commands it doesn't handle.Will send a Default Response for commands it can't handle.Currently does not support attribute reporting. envelope envelope from received message context pointer to attribute tree for cluster or NULL if the cluster doesn't have any attributes (typically passed in via endpoint dispatcher) 0 command was processed, including sending a possible response !0 error sending response or processing command
References zcl_command_build.
const char * zcl_status_text(uint_fast8_t status)
Converts a ZCL status byte (one of the ZCL_STATUS_* macros) into a string.
status status byte to convert pointer to an unmodifiable string with a description of the status
Referenced by zcl_command_dump.