aps.h
WPAN_STACK_PROFILE_PROPRIETARY
Network Specific.
WPAN_STACK_PROFILE_ZIGBEE
ZigBee (2006)
WPAN_STACK_PROFILE_ZIGBEE_PRO
ZigBee PRO (2007)
WPAN_PROFILE_ZDO
ZigBee Device Object (aka ZigBee Device Profile)
Referenced by _zdo_endpoint_of, _zdo_envelope_create, zdo_simple_desc_request, zdo_send_descriptor_req.
WPAN_PROFILE_SMART_ENERGY
Smart Energy Profile.
WPAN_PROFILE_DIGI
Digi International, mfg-specific.
Referenced by xbee_ota_init, xbee_transparent_serial.
WPAN_MANUFACTURER_DIGI
Digi International (MaxStream)
WPAN_MANUFACTURER_DIGI2
Digi International.
WPAN_MANUFACTURER_TEST1
Test Vendor #1.
WPAN_MANUFACTURER_TEST2
Test Vendor #2.
WPAN_MANUFACTURER_TEST3
Test Vendor #3.
WPAN_ENDPOINT_ZDO
ZigBee Device Object/Profile.
Referenced by _zdo_endpoint_of, _zdo_envelope_create, zdo_simple_desc_request, zdo_send_descriptor_req.
WPAN_ENDPOINT_DIGI_SE
Digi Smart Energy.
WPAN_ENDPOINT_DDO
Digi Device Objects.
WPAN_ENDPOINT_DIGI_DEVICE
WPAN_ENDPOINT_DIGI_DATA
Digi Data.
Referenced by xbee_ota_init, xbee_transparent_serial.
WPAN_ENDPOINT_BROADCAST
Broadcast Endpoint.
WPAN_SEND_FLAG_NONE
WPAN_SEND_FLAG_ENCRYPTED
WPAN_CLUST_FLAG_NONE
no flags
WPAN_CLUST_FLAG_INPUT
input/server cluster (typically receives requests)
WPAN_CLUST_FLAG_OUTPUT
output/client cluster (typically receives responses)
WPAN_CLUST_FLAG_INOUT
both client and server cluster
WPAN_CLUST_FLAG_SERVER
alias name for input cluster (uses ZCL terminology)
WPAN_CLUST_FLAG_CLIENT
alias name for output cluster (uses ZCL terminology)
WPAN_CLUST_FLAG_ENCRYPT
Data sent or received by this cluster must be encrypted.
Do not accept unencrypted broadcast messages. If using this flag on a non-ZCL cluster, be sure to set WPAN_CLUST_FLAG_NOT_ZCL as well.
Referenced by _xbee_ota_xmodem_write, xbee_ota_init, xbee_ota_server_cmd.
WPAN_CLUST_FLAG_ENCRYPT_UNICAST
Unicast data sent or received by this cluster must be encrypted, but unencrypted broadcast frames are OK.
If using this flag on a non-ZCL cluster, be sure to set WPAN_CLUST_FLAG_NOT_ZCL as well.
WPAN_CLUST_FLAG_NOT_ZCL
this cluster is NOT using the ZigBee Cluster Library (ZCL)
WPAN_ENVELOPE_CLUSTER_FLAGS
mask of WPAN_CLUST_FLAG_* flags for the cluster tied to this envelope
WPAN_ENVELOPE_BROADCAST_ADDR
frame was received on a broadcast address
Referenced by _xbee_handle_receive_explicit.
WPAN_ENVELOPE_BROADCAST_EP
frame was received on the broadcast endpoint (0xFF)
WPAN_ENVELOPE_RX_APS_ENCRYPT
frame was received with APS encryption
Referenced by xbee_ota_server_cmd, _xbee_handle_receive_explicit.
WPAN_CLUSTER_END_OF_LIST
Cluster ID used to mark the end of cluster_table in wpan_endpoint_table_entry_t.
Referenced by _match_desc_cluster_list, _simple_desc_cluster_list, wpan_cluster_match.
WPAN_CLUST_ENTRY_LIST_END
Macro for a wpan_cluster_table_entry_t that can be used to mark the end of the table.
WPAN_FLAG_NONE
WPAN_FLAG_JOINED
device has joined a network (but not necessarily authenticated)
WPAN_FLAG_AUTHENTICATED
device completed Key Establishment and can send APS encrypted frames
WPAN_FLAG_AUTHENTICATION_ENABLED
device has encryption enabled (EO non-zero)
WPAN_DEV_IS_JOINED
Macro to test whether a device has joined the network.
dev (wpan_dev_t FAR *) to test 0 device has not joined the network !0 device has joined the network
WPAN_DEV_IS_AUTHENTICATED
Macro to test whether a device has authenticated with the trust center.
dev (wpan_dev_t FAR *) to test 0 device has authenticated !0 device has not authenticated
WPAN_ENDPOINT_END_OF_LIST
Endpoint ID used to mark the end of endpoint_table in wpan_dev_t.
Referenced by wpan_endpoint_get_next.
WPAN_ENDPOINT_TABLE_END
Macro for a wpan_endpoint_table_entry_t that can be used to mark the end of the table.
WPAN_APS_PROFILE_ANY
WPAN_CONVERSATION_END
WPAN_CONVERSATION_CONTINUE
WPAN_MAX_CONVERSATIONS
Number of outstanding requests to track in a wpan_ep_state_t associated with an endpoint.
Referenced by wpan_conversation_register, wpan_conversation_response.
WPAN_CONVERSATION_TIMEOUT
Default conversation recycle timeout (seconds)
wpan_clust_digi
DigiMesh Sleeping Router Sync.
typedef int(* wpan_aps_handler_fn) (const wpan_envelope_t FAR *envelope, void FAR *context))(const wpan_envelope_t FAR *envelope, void FAR *context)
General handler used in the cluster table.
Dispatcher searches an endpoint's cluster table for a matching cluster, and hands the frame off to the cluster's handler.If the cluster's handler is set to NULL, or the frame is for a cluster ID that does not appear in the table, the dispatcher hands the frame off to the endpoint's handler. envelope information about the frame (addresses, endpoint, profile, cluster, etc.) context user context (from cluster table) 0 handled data !0 some sort of error processing data
typedef int(* wpan_ep_handler_fn) (const wpan_envelope_t FAR *envelope, struct wpan_ep_state_t FAR *ep_state))(const wpan_envelope_t FAR *envelope, struct wpan_ep_state_t FAR *ep_state)
General handler used in the endpoint table.
If a cluster's handler is set to NULL, or the frame is for a cluster ID that does not appear in the table, the dispatcher hands the frame off to the endpoint's handler. envelope information about the frame (addresses, endpoint, profile, cluster, etc.) ep_state pointer to endpoint state structure 0 handled data !0 some sort of error processing data
typedef int(* wpan_endpoint_send_fn) (const wpan_envelope_t FAR *envelope, uint16_t flags))(const wpan_envelope_t FAR *envelope, uint16_t flags)
Function called by the WPAN APS layer to send a frame out on the network.
This is part of the glue that links the XBee layer with the WPAN/ZigBee layers. envelope information about the frame (addresses, endpoint, profile, cluster, payload, etc.) flags flags related to sending, see WPAN_SEND_FLAG_* macros #WPAN_SEND_FLAG_NONE: no special behavior#WPAN_SEND_FLAG_ENCRYPTED: use APS layer encryption 0 frame sent !0 error sending frame -EMSGSIZE payload is too large TodoAdd support for a broadcast radius? Don't send Tx Status? Use frame ID 0?Todocome up with standard error codes for the following possible errors? outbound frame buffer is full, invalid data in envelope, payload is too big
typedef int(* _wpan_config_fn) (struct wpan_dev_t *dev,...))(struct wpan_dev_t *dev,...)
Function called by the WPAN APS layer to configure the underlying network device.
Exact implementation is currently undefined, but this entry exists for future expansion of the API. dev device to configure ... variable arguments to the function 0 configuration request processed successfully >0 error parsing parameter #retval
typedef int(* wpan_tick_fn) (struct wpan_dev_t *dev))(struct wpan_dev_t *dev)
Function called by the WPAN APS layer to have the underlying device read and dispatch frames.
dev device to tick number of frames processed during the tick
typedef const wpan_endpoint_table_entry_t*(* wpan_endpoint_get_next_fn) (struct wpan_dev_t *dev, const wpan_endpoint_table_entry_t *ep))(struct wpan_dev_t *dev, const wpan_endpoint_table_entry_t *ep)
Custom function for walking the endpoint table.
The application can define its own function to walk the endpoint table, possibly to support a dynamic table or a table where endpoints aren't always visible. dev device with endpoint table to walk ep NULL to return first entry in table, or a pointer previously returned by this function to get the next entry NULL dev is invalid or reached end of table !NULL next entry from table wpan_endpoint_match(), wpan_cluster_match(), wpan_endpoint_get_next()
typedef int(* wpan_response_fn) (struct wpan_conversation_t FAR *conversation, const wpan_envelope_t FAR *envelope))(struct wpan_conversation_t FAR *conversation, const wpan_envelope_t FAR *envelope)
Handler registered with wpan_conversation_register() to process responses to outstanding requests.
conversation Pointer to entry in conversation table. Handler can use the pointer to access the context and transaction ID from the conversation, or request deletion of the conversation via wpan_conversation_delete(). Never NULL. envelope envelope with response or NULL if there was a timeout WPAN_CONVERSATION_END end of conversation, no more responses expected WPAN_CONVERSATION_CONTINUE leave conversation open, more responses are expected
int wpan_tick(wpan_dev_t *dev)
Calls the underlying hardware tick function to process received frames, and times out expired conversations.
dev WPAN device to tick >=0 number of frames processed during the tick -EINVAL device does not have a tick function assigned to it <0 some other error encountered during the tick
References _wpan_endpoint_expire_conversations, EINVAL, wpan_endpoint_table_entry_t::ep_state, wpan_dev_t::tick, wpan_endpoint_get_next.
const wpan_cluster_table_entry_t * wpan_cluster_match(uint16_t match, uint8_t mask, const wpan_cluster_table_entry_t *entry)
Search a cluster table for a matching cluster ID.
match ID to match mask Flags to match against the flags member of the wpan_cluster_table_entry_t structure. If any flags match, the entry is returned. Typically one of WPAN_CLUST_FLAG_INPUT (or WPAN_CLUST_FLAG_SERVER)WPAN_CLUST_FLAG_OUTPUT (or WPAN_CLUST_FLAG_CLIENT) entry pointer to list of entries to search NULL entry is invalid or search reached WPAN_CLUSTER_END_OF_LIST without finding a match. !NULL Pointer to matching entry from table. wpan_endpoint_get_next(), wpan_endpoint_match()
References wpan_cluster_table_entry_t::cluster_id, wpan_cluster_table_entry_t::flags, WPAN_CLUSTER_END_OF_LIST.
const wpan_endpoint_table_entry_t * wpan_endpoint_get_next(wpan_dev_t *dev, const wpan_endpoint_table_entry_t *ep)
Function used to walk a device's endpoint table.
For most devices, this will just walk the entries in dev->endpoint_table. For custom applications a function may dynamically return entries.Use of this function is the only way to walk the endpoint table. dev device with endpoint table to walk ep NULL to return first entry in table, or a pointer previously returned by this function to get the next entry NULL dev is invalid or reached end of table !NULL next entry from table wpan_endpoint_match(), wpan_cluster_match()
References wpan_endpoint_table_entry_t::endpoint, wpan_dev_t::endpoint_get_next, wpan_dev_t::endpoint_table, WPAN_ENDPOINT_END_OF_LIST.
Referenced by wpan_tick.
const wpan_endpoint_table_entry_t * wpan_endpoint_match(wpan_dev_t *dev, uint8_t endpoint, uint16_t profile_id)
Walk a device's endpoint table looking for a matching endpoint ID and profile ID.
Used by the endpoint dispatcher and ZDO layer to describe available endpoints on this device. dev Device with endpoint table to search. endpoint Endpoint number to search for. profile_id Profile to match or WPAN_APS_PROFILE_ANY to search on endpoint number only. NULL dev is invalid or reached end of table without finding a match !NULL next entry from table wpan_endpoint_of_cluster(), wpan_endpoint_get_next(), wpan_cluster_match(), wpan_endpoint_of_envelope()
Referenced by _zdo_endpoint_of, wpan_conversation_response, wpan_endpoint_of_envelope.
const wpan_endpoint_table_entry_t * wpan_endpoint_of_envelope(const wpan_envelope_t *env)
Look up the endpoint table entry for the source endpoint of an envelope.
env Envelope for lookup. Uses env->source_endpoint and env->profile_id to find the endpoint table entry for env->dev. NULL invalid parameter, or reached end of table without finding a match !NULL entry from table wpan_endpoint_of_cluster(), wpan_endpoint_get_next(), wpan_cluster_match(), wpan_endpoint_match()
References wpan_envelope_t::dev, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, wpan_endpoint_match.
const wpan_endpoint_table_entry_t * wpan_endpoint_of_cluster(wpan_dev_t *dev, uint16_t profile_id, uint16_t cluster_id, uint8_t mask)
Walk a device's endpoint table looking for a matching profile ID and cluster ID.
Used to find the correct endpoint to use for sending ZCL client requests. dev Device with endpoint table to search. profile_id Profile to match or WPAN_APS_PROFILE_ANY to search on cluster ID only. cluster_id Cluster ID to search for. mask Flags to match against the flags member of the wpan_cluster_table_entry_t structure. If any flags match, the entry is returned. Typically one of WPAN_CLUST_FLAG_INPUT (or WPAN_CLUST_FLAG_SERVER)WPAN_CLUST_FLAG_OUTPUT (or WPAN_CLUST_FLAG_CLIENT) NULL dev is invalid or reached end of table without finding a match !NULL matching entry from table wpan_endpoint_match(), wpan_endpoint_get_next(), wpan_cluster_match()
void wpan_envelope_create(wpan_envelope_t *envelope, wpan_dev_t *dev, const addr64 FAR *ieee, uint16_t network_addr)
Starting with a blank envelope, fill in the device, 64-bit IEEE address and 16-bit network address of the destination.
The profile ID, cluster ID, source/destination endpoints and envelope options are all be set to zero. envelope envelope to populate dev device that will send this envelope ieee 64-bit IEEE/MAC address of recipient or one of WPAN_IEEE_ADDR_COORDINATOR (send to coordinator)WPAN_IEEE_ADDR_BROADCAST (broadcast packet)WPAN_IEEE_ADDR_UNDEFINED (use network address only) network_addr 16-bit network address of recipient or one of WPAN_NET_ADDR_COORDINATOR for the coordinator (use the coordinator's actual IEEE address for the ieee parameter).WPAN_NET_ADDR_BCAST_ALL_NODES (broadcast to all nodes)WPAN_NET_ADDR_BCAST_NOT_ASLEEP (broadcast to awake nodes)WPAN_NET_ADDR_BCAST_ROUTERS (broadcast to routers/coordinator)WPAN_NET_ADDR_UNDEFINED (use 64-bit address only) When sending broadcast packets, use WPAN_IEEE_ADDR_BROADCAST and WPAN_NET_ADDR_UNDEFINED. Don't set both addresses to broadcast.When using DigiMesh protocol, always set the network_addr to WPAN_NET_ADDR_UNDEFINED.wpan_envelope_reply()
References wpan_envelope_t::dev, wpan_envelope_t::ieee_address, wpan_envelope_t::network_address.
Referenced by _xbee_ota_xmodem_write, _zdo_envelope_create, xbee_ota_init, zdo_send_ieee_addr_req.
int wpan_envelope_reply(wpan_envelope_t FAR *reply, const wpan_envelope_t FAR *original)
Create a reply envelope based on the envelope received from a remote node.
Copies the interface, addresses, profile and cluster from the original envelope, and then swaps the source and destination endpoints.Note that it may be necessary for the caller to change the cluster_id as well, after building the reply envelope. For example, ZDO responses set the high bit of the request's cluster ID. reply Buffer for storing the reply envelope. original Original envelope, received from a remote node, to base the reply on. 0 addressed reply envelope -EINVAL either parameter is NULL or they point to the same address wpan_envelope_create()
References EINVAL.
Referenced by xbee_ota_server_cmd, zcl_comm_response, zdo_send_response.
int wpan_envelope_send(const wpan_envelope_t FAR *envelope)
Send a message to an endpoint using address and payload information stored in a wpan_envelope_t structure.
envelope envelope of request to send 0 request sent !0 error trying to send request
Referenced by _zcl_comm_command_send, xbee_ota_server_cmd, xbee_transparent_serial, zcl_comm_response, zdo_send_descriptor_req, zdo_simple_desc_request.
void wpan_envelope_dump(const wpan_envelope_t FAR *envelope)
Debugging function to dump the contents of an envelope to stdout.
Displays all fields from the envelope, plus the contents of the payload envelope envelope to dump
References addr64_format, ADDR64_STRING_LENGTH, hex_dump, HEX_DUMP_FLAG_OFFSET, PRIsFAR.
int wpan_conversation_register(wpan_ep_state_t FAR *state, wpan_response_fn handler, const void FAR *context, uint16_t timeout)
Add a conversation to the table of tracked conversations.
state endpoint state associated with sending endpoint handler handler to call when responses come back, or NULL to increment and return the endpoint's transaction ID context pointer stored in conversation table and passed to callback handler timeout number of seconds before generating timeout, or 0 for none 0-255 transaction ID to use in sent frame -EINVAL state is invalid (NULL) -ENOSPC table is full wpan_endpoint_next_trans
References EINVAL, FAR, WPAN_MAX_CONVERSATIONS.
Referenced by zdo_send_bind_req, zdo_send_descriptor_req, zdo_send_ieee_addr_req, zdo_send_nwk_addr_req, zdo_simple_desc_request.
int wpan_conversation_response(wpan_ep_state_t FAR *state, uint8_t transaction_id, const wpan_envelope_t FAR *envelope)
Searches the endpoint's table of active conversations (outstanding requests waiting for responses) for a given transaction.
Hands the response frame off to the handler registered to the conversation with wpan_conversation_register(). state endpoint state (from endpoint table) or NULL to look it up using the envelope transaction_id transaction ID from frame payload, used to look up conversation envelope envelope from response frame, passed to conversation's handler -EINVAL invalid parameter passed to function, or conversation not found in table 0 handler processed response !0 handler reported an error while processing response
References EINVAL, wpan_endpoint_table_entry_t::ep_state, FAR, wpan_endpoint_match, WPAN_MAX_CONVERSATIONS.
uint8_t wpan_endpoint_next_trans(const wpan_endpoint_table_entry_t *ep)
Increment and return the endpoint's transaction ID counter.
ep entry from endpoint table 0-255 current transaction ID for endpoint
References wpan_endpoint_table_entry_t::ep_state.
int wpan_envelope_dispatch(wpan_envelope_t *envelope)
Find the matching endpoint for the provided envelope and have it process the frame.
In the case of the broadcast endpoint (255), dispatches the frame to all endpoints matching the envelope's profile ID.Looks up the destination endpoint and cluster ID in the device's endpoint table and passes envelope off to the cluster handler (if a matching cluster was found) or the endpoint handler. envelope structure containing all necessary information about message (endpoints, cluster, profile, etc.) 0 successfully dispatched message -ENOENT no handler for this endpoint/cluster !0 error dispatching messages
References ENOENT.
Referenced by _xbee_handle_receive_explicit.
void wpan_conversation_delete(wpan_conversation_t FAR *conversation)
Delete a conversation from an endpoint's conversation table.
conversation conversation to delete