device.h
XBEE_DEV_FLAG_NONE
XBEE_RX_OPT_ACKNOWLEDGED
XBee Receive Options: packet was acknowledged [ZigBee, DigiMesh].
XBEE_RX_OPT_BROADCAST
XBee Receive Options: broadcast packet [ZigBee, DigiMesh].
Referenced by _xbee_handle_receive_explicit.
XBEE_RX_OPT_APS_ENCRYPT
XBee Receive Options: APS-encrypted packet [ZigBee].
Referenced by _xbee_handle_receive_explicit.
XBEE_RX_OPT_FROM_END_DEVICE
XBee Receive Options: packet from end device (if known) [ZigBee].
XBEE_RX_OPT_MODE_MASK
XBee Receive Options: Mask for transmission mode [DigiMesh].
XBEE_RX_OPT_MODE_NONE
XBee Receive Options: Mode not specified [DigiMesh].
XBEE_RX_OPT_MODE_POINT_MULTIPOINT
XBee Receive Options: Point-Multipoint [DigiMesh].
XBEE_RX_OPT_MODE_REPEATER
XBee Receive Options: Repeater Mode [DigiMesh].
XBEE_RX_OPT_MODE_DIGIMESH
XBee Receive Options: DigiMesh (not available on 10k product) [DigiMesh].
typedef int(* xbee_frame_handler_fn) (struct xbee_dev_t *xbee, const void FAR *frame, uint16_t length, void FAR *context))(struct xbee_dev_t *xbee, const void FAR *frame, uint16_t length, void FAR *context)
Standard API for an XBee frame handler in xbee_frame_handlers global.
These functions are only called when xbee_dev_tick() or wpan_tick() are called and a complete frame is ready for processing.There isn't an actual xbee_frame_handler_fn function in the XBee libraries. This documentation exists as a template for writing frame handlers. xbee XBee device that received frame. frame Pointer to frame data. Data starts with the frame type (the 0x7E start byte and frame length are stripped by lower layers of the driver). length Number of bytes in frame. context Handler-specific "context" value, chosen when the handler was registered with xbee_frame_handler_add. 0 successfully processed frame !0 error processing frame
typedef int(* xbee_is_awake_fn) (struct xbee_dev_t *xbee))(struct xbee_dev_t *xbee)
Function to check the XBee device's AWAKE pin to see if it is awake.
xbee XBee device that received frame !0 XBee module is awake. 0 XBee module is asleep.
typedef void(* xbee_reset_fn) (struct xbee_dev_t *xbee, bool_t asserted))(struct xbee_dev_t *xbee, bool_t asserted)
Function to toggle the /RESET pin to the XBee device.
xbee XBee device that received frame asserted non-zero to assert /RESET, zero to de-assert
typedef void(* xbee_disc_node_id_fn) (struct xbee_dev_t *xbee, const struct xbee_node_id_t *rec))(struct xbee_dev_t *xbee, const struct xbee_node_id_t *rec)
Function to process parsed Node ID messages.
Programs can register a Node ID message handler with this signature to receive Node ID messages (either from ATND responses, Join Notifications, or as a result of Commissioning Button presses). xbee XBee device that received the message rec parsed Node ID message or NULL if a targeted discovery timed out xbee_disc_add_node_id_handler, xbee_disc_remove_node_id_handler, xbee_disc_discover_nodes
XBEE_MODEM_STATUS_HW_RESET
XBee Modem Status: Hardware reset [ZigBee, DigiMesh, Wi-Fi].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_WATCHDOG
XBee Modem Status: Watchdog timer reset [ZigBee, DigiMesh, Wi-fi].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_JOINED
XBee Modem Status: Joined network (routers and end devices) [ZigBee, Wi-Fi].
Referenced by _xbee_cmd_modem_status, xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_DISASSOC
XBee Modem Status: Disassociated (left network) [ZigBee, Wi-Fi].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_IP_CONFIG_ERROR
XBee Modem Status: IP configuration error [Wi-Fi].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_COORD_START
XBee Modem Status: Coordinator started [ZigBee].
Referenced by _xbee_cmd_modem_status, xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_NETWORK_KEY_UPDATED
XBee Modem Status: Network security key was updated [ZigBee].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_WOKE_UP
XBee Modem Status: Network Woke Up [DigiMesh].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_SLEEPING
XBee Modem Status: Network Went To Sleep [DigiMesh].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_OVERVOLTAGE
XBee Modem Status: Voltage supply limit exceeded (XBee-PRO only) [ZigBee].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_CLOUD_CONNECTED
XBee Modem Status: Device Cloud connected [Wi-Fi].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_CLOUD_DISCONNECTED
XBee Modem Status: Device Cloud disconnected [Wi-Fi].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_KEY_ESTABLISHED
XBee Modem Status: Key establishment complete [Smart Energy].
Referenced by _xbee_cmd_modem_status, xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_CONFIG_CHANGE_IN_JOIN
XBee Modem Status: Modem config changed while join in progress [ZigBee].
Referenced by xbee_frame_dump_modem_status.
XBEE_MODEM_STATUS_STACK_ERROR
XBee Modem Status: Network stack error [ZigBee].
Referenced by xbee_frame_dump_modem_status.
XBEE_HARDWARE_MASK
XBEE_HARDWARE_S1
XBEE_HARDWARE_S1_PRO
XBEE_HARDWARE_S2
XBEE_HARDWARE_S2_PRO
XBEE_HARDWARE_900_PRO
XBEE_HARDWARE_868_PRO
XBEE_HARDWARE_S2B_PRO
XBEE_HARDWARE_S2C_PRO
XBEE_HARDWARE_S2C
XBEE_HARDWARE_S3B
XBEE_HARDWARE_S8
XBEE_HARDWARE_S6B
XBEE_PROTOCOL_MASK
XBEE_PROTOCOL_ZNET
XBEE_PROTOCOL_ZB
XBEE_PROTOCOL_SMARTENERGY
XBEE_PROTOCOL_ZB_S2C
XBEE_PROTOCOL_SE_S2C
XBEE_PROTOCOL_MESHLESS
XBEE_PROTOCOL_DIGIMESH
XBEE_NODETYPE_MASK
XBEE_NODETYPE_COORD
XBEE_NODETYPE_ROUTER
XBEE_NODETYPE_ENDDEV
XBEE_DEV_MAX_DISPATCH_PER_TICK
Maximum number of frames to dispatch per call to xbee_tick().
XBEE_MAX_RFPAYLOAD
Max payload for all supported XBee types is 256 bytes.
Actual firmware used may affect that size, and even enabling encryption can have an affect. Smart Energy and ZigBee are limited to 128 bytes, DigiMesh is 256 bytes.
XBEE_MAX_RX_FRAME_LEN
Max Received Frame Size, including type, is for 0x91, Receive Explicit.
XBEE_MAX_TX_FRAME_LEN
XBEE_MAX_TX_FRAME_LEN
Max Transmitted Frame Size, including type, is for 0x11, Transmit Explicit.
XBEE_MAX_RX_FRAME_LEN
XBEE_MAX_FRAME_LEN
Deprecated legacy macro, use XBEE_MAX_RX_FRAME_LEN instead.
XBEE_DEV_STACK_VERSION_ADDR
Macro function to get a pointer to the LSB of the radio's firmware version.
Typically used to define ZCL_STACK_VERSION_ADDR for the Basic cluster. x name of xbee_dev_t to reference firmware_version from. address of the low byte of the firmware version, taking the processor's endian-ness into account
XBEE_FRAME_TABLE_END
XBEE_DEV_DUMP_FLAG_NONE
XBEE_DEV_DUMP_FLAG_DEFAULT
XBEE_WRITE_FLAG_NONE
XBEE_FRAME_MODEM_STATUS_DEBUG
Add this macro to the list of XBee frame handlers to have modem status changes dumped to STDOUT.
xbee_frame_type
Send an AT Command to the local device (see xbee_atcmd.c, xbee_header_at_request_t).
[ZigBee, DigiMesh]
xbee_dev_rx_state
waiting for initial 0x7E
xbee_dev_flags
xbee_cmd_init called
xbee_dev_mode
Haven't started communicating with XBee yet.
xbee_frame_modem_status_t
const xbee_dispatch_table_entry_t xbee_frame_handlers[][]
Static table used for dispatching frames.
The application needs to define this table, and it should end with the XBEE_FRAME_TABLE_END marker.
Referenced by _xbee_dispatch_table_dump.
uint8_t status
uint8_t xbee_next_frame_id(xbee_dev_t *xbee)
Increment and return current frame ID for a given XBee device.
Frame IDs go from 1 to 255 and then back to 1. xbee XBee device. 1-255 Current frame ID (after incrementing) for device 0 xbee is not a valid XBee device pointer.
References xbee_dev_t::frame_id.
Referenced by xbee_cmd_send.
int xbee_dev_init(xbee_dev_t *xbee, const xbee_serial_t *serport, xbee_is_awake_fn is_awake, xbee_reset_fn reset)
Initialize the XBee device structure and open a serial connection to a local, serially-attached XBee module.
This function does not actually initiate communications with the XBee module. See xbee_cmd_init_device() for information on initializing the "AT Command" layer of the driver, which will read basic information from the XBee module. xbee XBee device to initialize. serport Pointer to an xbee_serial_t structure used to initialize xbee->serport. is_awake Pointer to function that reads the XBee module's "ON" pin. The function should return 1 if XBee is on and 0 if it is off. intis_awake(xbee_dev_t*xbee); reset Pointer to function that asserts the XBee module's "/RESET" pin. If asserted is TRUE, puts the XBee into reset. If asserted is FALSE, takes it out of reset. No return value. voidxbee_reset(xbee_dev_t*xbee,bool_tasserted); 0 Success -EINVAL Invalid parameter (xbee is NULL, serport is not valid, etc.) -EIO Couldn't set serial port baudrate within 5% of serport->baudrate.
References EINVAL, xbee_dev_t::flags, xbee_dev_t::is_awake, xbee_dev_t::reset, xbee_dev_t::serport, XBEE_DEV_FLAG_USE_FLOWCONTROL, XBEE_PLATFORM_INIT, xbee_ser_flowcontrol, xbee_ser_open.
void xbee_dev_dump_settings(xbee_dev_t *xbee, uint16_t flags)
Print information to stdout about the XBee device.
Default behavior is to print the name of the serial port, the XBee module's hardware version (ATHV), firmware version (ATVR), IEEE address (ATSH/ATSL) and network address (ATMY).Assumes the user has already called xbee_cmd_init_device() and waited for xbee_cmd_query_status() to finish. xbee flags XBEE_DEV_DUMP_FLAG_NONE: default settings xbee_cmd_init_device(), xbee_cmd_query_status(), xbee_ser_portname()
int xbee_dev_reset(xbee_dev_t *xbee)
Toggles the reset line of the XBee device.
xbee XBee device to reset. 0 Successfully toggled reset. -EINVAL Invalid xbee_dev_t passed to function. -EIO This XBee device doesn't have an interface to the module's reset pin.
References EINVAL, EIO, xbee_dev_t::reset, XBEE_SET_TIMEOUT_MS.
int xbee_dev_tick(xbee_dev_t *xbee)
Check for newly received frames on an XBee device and dispatch them to registered frame handlers.
A program with an XBee interface needs to call this function often enough to keep up with inbound bytes.Execution time depends greatly on how long each frame handler takes to process its frame.This function is NOT re-entrant and will return -EBUSY if it is called when already running. xbee XBee device to check for, and then dispatch, new frames. >=0 Number of frames received and dispatched. -EINVAL If xbee isn't a valid device structure. -EBUSY If xbee_dev_tick() was called when it's already running for this device.
References _xbee_frame_load, EBUSY, EINVAL, xbee_dev_t::flags, INTERRUPT_DISABLE, INTERRUPT_ENABLE, XBEE_DEV_FLAG_IN_TICK.
Referenced by _xbee_wpan_tick.
int xbee_frame_write(xbee_dev_t *xbee, const void FAR *header, uint16_t headerlen, const void FAR *data, uint16_t datalen, uint16_t flags)
Copies a frame into the transmit serial buffer to send to an XBee module.
Header should include bytes as they will be sent to the XBee. Function accepts separate header and data to limit the amount of copying necessary to send requests.This function should only be called after xbee has been initialized by calling xbee_dev_init().By default, xbee_frame_write() checks the /CTS signal from the XBee before attempting to send, and will return -EBUSY if the XBee has deasserted CTS. Use xbee_dev_flowcontrol() to disable this check (necessary on a system without a connection to the XBee module's /CTS signal). xbee XBee device to send to. header Pointer to the header to send. Header starts with the frame type (this function will pre-pend the 0x7E start-of-frame and 16-bit length). Pass NULL if there isn't a header and the entire frame is in the payload (data and datalen). headerlen Number of header bytes to send (starting with address passed in header). Ignored if header is NULL. data Address of frame payload or NULL if the entire frame content is stored in the header bytes (header and headerlen). datalen Number of payload bytes to send (starting with address passed in data). Ignored if data is NULL. flags Optional flags XBEE_WRITE_FLAG_NONE 0 Successfully queued frame in transmit serial buffer. -EINVAL xbee is NULL or invalid flags passed -ENODATA No data to send (headerlen + datalen == 0). -EBUSY Transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal). -EMSGSIZE Serial buffer can't ever send a frame this large. xbee_dev_init(), xbee_serial_write(), xbee_dev_flowcontrol()
void xbee_dev_flowcontrol(xbee_dev_t *xbee, bool_t enabled)
Control whether xbee_frame_write() checks the XBee CTS signal before sending frames.
Flow control is enabled in xbee_dev_init() by default. xbee XBee to configure enabled TRUE to enable checking CTS before sending xbee_dev_init(), xbee_frame_write()
References xbee_dev_t::flags, XBEE_DEV_FLAG_USE_FLOWCONTROL.
void _xbee_dispatch_table_dump(const xbee_dev_t *xbee)
Dump the contents of the frame dispatch table for XBee device xbee. Must have XBEE_DEVICE_VERBOSE defined. xbee XBee device of table to dump.
References xbee_dispatch_table_entry_t::frame_id, xbee_dispatch_table_entry_t::frame_type, PRIpFAR, xbee_frame_handlers, XBEE_UNUSED_PARAMETER.
uint8_t _xbee_checksum(const void FAR *bytes, uint16_t length, uint_fast8_t initial)
Calculate the checksum for an XBee frame.
This function actually subtracts bytes from 0xFF, in order to determine the proper checksum byte so all bytes added together result in 0x00.Frame checksums start with the frame type (first byte after frame length).If calculating a checksum for an outgoing packet, sum all of the bytes using this function, and send the low byte of the result.If verifying a received packet, summing all of the bytes after the length, including the packet's checksum byte, should result in 0x00.Should only be used internally by this library. bytes Buffer of bytes to add to sum, assumed non-NULL. length Number of bytes to add. initial Starting checksum value. Use 0xFF to start or the result of the previous call if summing multiple blocks of data. Value from 0x00 to 0xFF that, when added to all bytes previously checksummed, results in a low byte of 0x00.
int _xbee_frame_load(xbee_dev_t *xbee)
Check XBee's serial buffer for complete frames and pass them off to the dispatcher.
Should only be called after xbee has been initialized by calling xbee_dev_init(). Typically called by xbee_dev_tick(). xbee XBee device to read from. 0 No new frames waiting. >0 Number of frames processed. <0 Error. xbee_dev_init(), _xbee_frame_dispatch()
References length, xbee_dev_t::serport, xbee_ser_invalid.
Referenced by xbee_dev_tick.
int _xbee_frame_dispatch(xbee_dev_t *xbee, const void FAR *frame, uint16_t length)
Function called by _xbee_frame_load() to dispatch any frames read.
Scans through xbee->frame_handlers, matching the frame_type and frame_id (if frame_id is not zero). Passes the frame and context (from the frame handler table) to each matching handler. xbee XBee device that received the frames. frame Address of bytes in frame, starting with the frame type byte. Note that the frame is still in network byte order it is exactly as received from the XBee module. length Number of bytes in frame. Currently returns 0 in all cases. May be updated at some point with various error messages (e.g., no handlers are registered for the given frame type and ID) or the number of handlers it was dispatched to -EINVAL Invalid parameter >=0 number of handlers frame was dispatched to
References _xbee_dev_modem_status, EINVAL, FAR, xbee_dev_t::wpan_dev, XBEE_FRAME_MODEM_STATUS.
int xbee_frame_dump_modem_status(xbee_dev_t *xbee, const void FAR *frame, uint16_t length, void FAR *context)
Frame handler for 0x8A (XBEE_FRAME_MODEM_STATUS) frames dumps modem status to STDOUT for debugging purposes.
View the documentation of xbee_frame_handler_fn() for this function's parameters and return value.XBEE_FRAME_MODEM_STATUS_DEBUG, xbee_frame_handler_fn()
References EINVAL, FAR, payload, XBEE_MODEM_STATUS_CLOUD_CONNECTED, XBEE_MODEM_STATUS_CLOUD_DISCONNECTED, XBEE_MODEM_STATUS_CONFIG_CHANGE_IN_JOIN, XBEE_MODEM_STATUS_COORD_START, XBEE_MODEM_STATUS_DISASSOC, XBEE_MODEM_STATUS_HW_RESET, XBEE_MODEM_STATUS_IP_CONFIG_ERROR, XBEE_MODEM_STATUS_JOINED, XBEE_MODEM_STATUS_KEY_ESTABLISHED, XBEE_MODEM_STATUS_NETWORK_KEY_UPDATED, XBEE_MODEM_STATUS_OVERVOLTAGE, XBEE_MODEM_STATUS_SLEEPING, XBEE_MODEM_STATUS_STACK_ERROR, XBEE_MODEM_STATUS_WATCHDOG, XBEE_MODEM_STATUS_WOKE_UP, XBEE_UNUSED_PARAMETER.