xbee_xmodem.c
_xmodem_debug
_xmodem_debug int _xbee_xmodem_ser_read(void FAR *context, void FAR *buffer, int16_t bytes)
_xmodem_debug int _xbee_xmodem_ser_write(void FAR *context, const void FAR *buffer, int16_t bytes)
int xbee_xmodem_use_serport(xbee_xmodem_state_t *xbxm, xbee_serial_t *serport)
Used for xmodem transfers over a simple serial port.
Associates the serial port with the xbee_xmodem_state_t and sets stream.read and stream.write function pointers to helper functions that read/write a serial port.Must be called before xbee_xmodem_tx_tick() and either before or after xbee_xmodem_tx_init(). xbxm state object to configure for serial read/write serport port to use for transfer 0 successfully associated serport with xbxm -EINVAL NULL parameter passed in <0 error assigning serport to xbxm xbee_ota_init, xbee_xmodem_set_stream
References xbee_xmodem_set_stream.
int xbee_xmodem_set_stream(xbee_xmodem_state_t *xbxm, xbee_xmodem_read_fn read, xbee_xmodem_write_fn write, const void FAR *context)
Configure the stream used to communicate with the target.
Associates function pointers and a context that are used to send data to and receive data from the target (device receiving data via Xmodem). xbxm state structure to configure read function used to read bytes from the target write function used to send bytes to the target context context passed to read and write functions 0 successfully configured communication path to target -EINVAL invalid parameter passed in xbee_ota_init, xbee_xmodem_use_serport
References xbee_xmodem_state_t::context, EINVAL, FAR, xbee_xmodem_state_t::read, xbee_xmodem_state_t::stream, xbee_xmodem_state_t::write.
Referenced by xbee_xmodem_use_serport.
int xbee_xmodem_set_source(xbee_xmodem_state_t *xbxm, void FAR *buffer, xbee_xmodem_read_fn read, const void FAR *context)
Configure the data source for the Xmodem send.
xbxm state structure to configure buffer buffer for use by xbee_xmodem_tx_tick must be at least 5 bytes larger than the block size passed to xbee_xmodem_tx_init() read function used to read bytes to send to the target context context passed to read function 0 successfully configured data source -EINVAL invalid parameter passed in
References _xbee_xmodem_getchar, _xbee_xmodem_putchar, xbee_xmodem_state_t::buffer, xbee_xmodem_state_t::context, EINVAL, FAR, xbee_xmodem_state_t::file, xbee_xmodem_state_t::read.
_xmodem_debug int _xbee_xmodem_getchar(xbee_xmodem_state_t *xbxm)
Helper function to read a single character from the stream. xbxm state structure 0-255 character read from stream -ENODATA stream is empty <0 error reading from stream
References xbee_xmodem_state_t::context, ENODATA, xbee_xmodem_state_t::read, xbee_xmodem_state_t::stream.
Referenced by xbee_xmodem_set_source.
_xmodem_debug int _xbee_xmodem_putchar(xbee_xmodem_state_t *xbxm, uint8_t ch)
Helper function to write a single character to the stream. xbxm state structure ch character to write 0 character was written to stream -ENOSPC could not write to stream <0 error writing to stream
References xbee_xmodem_state_t::context, ENOSPC, xbee_xmodem_state_t::stream, xbee_xmodem_state_t::write.
Referenced by xbee_xmodem_set_source.
int xbee_xmodem_tx_init(xbee_xmodem_state_t *xbxm, uint16_t flags)
Initialize state structure for use with xbee_xmodem_tx_tick() to send a file via Xmodem.
xbxm state structure to initialize flags one of the following macros, indicating the block size to use for the transfer XBEE_XMODEM_FLAG_NONEXBEE_XMODEM_FLAG_64XBEE_XMODEM_FLAG_128XBEE_XMODEM_FLAG_1024 -EINVAL invalid parameter passed in 0 initialized state, can pass it to xbee_xmodem_tx_tick xbee_ota_init
_xmodem_debug int _assemble_packet(xbee_xmodem_state_t *xbxm, uint16_t block_size)
_xmodem_debug uint16_t _block_size(xbee_xmodem_state_t *xbxm)
int xbee_xmodem_tx_tick(xbee_xmodem_state_t *xbxm)
Function to drive the Xmodem send state machine.
Call until it returns a non-zero result. -EINVAL invalid parameter passed in -ETIMEDOUT connection timed out waiting for data from target <0 error on send, transfer aborted 0 transfer in progress, call function again 1 transfer completed successfully
References xbee_xmodem_state_t::buffer, EINVAL, ETIMEDOUT, XMODEM_CAN.