xbee_wpan.c
xbee_wpan_debug
int _xbee_handle_receive_explicit(xbee_dev_t *xbee, const void FAR *raw, uint16_t length, void FAR *context)
Process XBee "Receive Explicit" frames (type 0x91) and hand off to wpan_envelope_dispatch() for further processing.
Please view the function help for xbee_frame_handler_fn() for details on this function's parameters and possible return values.
References _xbee_endpoint_send, be16toh, wpan_envelope_t::cluster_id, wpan_envelope_t::dest_endpoint, wpan_envelope_t::dev, EBADMSG, EINVAL, FAR, wpan_envelope_t::ieee_address, wpan_envelope_t::length, wpan_envelope_t::network_address, payload, wpan_envelope_t::payload, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, xbee_dev_t::wpan_dev, WPAN_ENVELOPE_BROADCAST_ADDR, wpan_envelope_dispatch, WPAN_ENVELOPE_RX_APS_ENCRYPT, XBEE_RX_OPT_APS_ENCRYPT, XBEE_RX_OPT_BROADCAST, XBEE_UNUSED_PARAMETER.
xbee_wpan_debug int _xbee_endpoint_send(const wpan_envelope_t FAR *envelope, uint16_t flags)
Sends data to an endpoint/profile/cluster on a remote WPAN node. See wpan_endpoint_send_fn() for parameters and return values.User code should use wpan_envelope_send() instead of calling this function directly.
Referenced by _xbee_handle_receive_explicit, xbee_wpan_init.
xbee_wpan_debug int _xbee_wpan_tick(wpan_dev_t *dev)
Simple stub function for the wpan_dev_t object to map the generic "tick wpan_dev_t" call into a "tick xbee_dev_t" call.Note that this works because the xbee_dev_t structure starts with a wpan_dev_t structure, so the wpan_dev_t address is the same as the xbee_dev_t address.See wpan_tick_fn() for parameters and return value.
References xbee_dev_tick.
Referenced by xbee_wpan_init.
int xbee_wpan_init(xbee_dev_t *xbee, const wpan_endpoint_table_entry_t *ep_table)
Configure xbee_dev_t for APS-layer (endpoint/cluster) networking.
If using this layer, be sure to call wpan_tick (instead of xbee_dev_tick) so it can manage the APS layers of the network stack. xbee device to configure ep_table pointer to an endpoint table to use with device 0 success -EINVAL invalid parameter passed to function
References _xbee_endpoint_send, _xbee_wpan_tick, EINVAL, wpan_dev_t::endpoint_send, wpan_dev_t::endpoint_table, wpan_dev_t::tick, xbee_dev_t::wpan_dev.
xbee_wpan_debug int _xbee_handle_transmit_status(xbee_dev_t *xbee, const void FAR *payload, uint16_t length, void FAR *context)
Dummy frame handler for 0x8B (XBEE_FRAME_TRANSMIT_STATUS) frames. Placeholder until we integrate processing of those frames into the stack. xbee_frame_handler_fn() TodoFigure out what needs to happen with these frames. Does atcmd layer need to pass errors down to callbacks? Registered endpoints? Tracked conversations?
References XBEE_UNUSED_PARAMETER.
int xbee_frame_dump_transmit_status(xbee_dev_t *xbee, const void FAR *payload, uint16_t length, void FAR *context)
Frame handler for 0x8B (XBEE_FRAME_TRANSMIT_STATUS) frames dumps transmit status to STDOUT for debugging purposes.
View the documentation of xbee_frame_handler_fn() for this function's parameters and return value.XBEE_FRAME_TRANSMIT_STATUS_DEBUG, xbee_frame_handler_fn()
References FAR, payload, XBEE_UNUSED_PARAMETER.