zcl.h
ZCL_CLUST_BASIC
ZCL_CLUST_POWER_CONFIG
ZCL_CLUST_DEVICE_TEMP_CONFIG
ZCL_CLUST_IDENTIFY
ZCL_CLUST_GROUPS
ZCL_CLUST_SCENES
ZCL_CLUST_ONOFF
ZCL_CLUST_ONOFF_SWITCH_CONFIG
ZCL_CLUST_LEVEL_CONTROL
ZCL_CLUST_ALARMS
ZCL_CLUST_TIME
ZCL_CLUST_RSSI_LOCATION
ZCL_CLUST_ANALOG_IN
ZCL_CLUST_ANALOG_OUT
ZCL_CLUST_ANALOG_VALUE
ZCL_CLUST_BINARY_IN
ZCL_CLUST_BINARY_OUT
ZCL_CLUST_BINARY_VALUE
ZCL_CLUST_MULTI_IN
ZCL_CLUST_MULTI_OUT
ZCL_CLUST_MULTI_VALUE
ZCL_CLUST_COMMISSIONING
ZCL_CLUST_SHADE_CONFIG
ZCL_CLUST_PUMP_CONFIG
ZCL_CLUST_THERMOSTAT
ZCL_CLUST_FAN_CONTROL
ZCL_CLUST_DEHUMIDIFY_CONTROL
ZCL_CLUST_THERMOSTAT_UI_CONFIG
ZCL_CLUST_COLOR_CONTROL
ZCL_CLUST_BALLAST_CONFIG
ZCL_CLUST_ILLUM_MEASURE
ZCL_CLUST_ILLUM_LEVEL_SENSING
ZCL_CLUST_TEMP_MEASURE
ZCL_CLUST_PRESSURE_MEASURE
ZCL_CLUST_FLOW_MEASURE
ZCL_CLUST_HUMIDITY_MEASURE
ZCL_CLUST_OCCUPANCY_SENSING
ZCL_CLUST_IAS_ZONE
ZCL_CLUST_IAS_ACE
ZCL_CLUST_IAS_WD
ZCL_CLUST_GENERIC_TUNNEL
ZCL_CLUST_BACNET_TUNNEL
ZCL_CLUST_BACNET_REG_ANALOG_IN
ZCL_CLUST_BACNET_EXT_ANALOG_IN
ZCL_CLUST_BACNET_REG_ANALOG_OUT
ZCL_CLUST_BACNET_EXT_ANALOG_OUT
ZCL_CLUST_BACNET_REG_ANALOG_VALUE
ZCL_CLUST_BACNET_EXT_ANALOG_VALUE
ZCL_CLUST_BACNET_REG_BINARY_IN
ZCL_CLUST_BACNET_EXT_BINARY_IN
ZCL_CLUST_BACNET_REG_BINARY_OUT
ZCL_CLUST_BACNET_EXT_BINARY_OUT
ZCL_CLUST_BACNET_REG_BINARY_VALUE
ZCL_CLUST_BACNET_EXT_BINARY_VALUE
ZCL_CLUST_BACNET_REG_MULTI_IN
ZCL_CLUST_BACNET_EXT_MULTI_IN
ZCL_CLUST_BACNET_REG_MULTI_OUT
ZCL_CLUST_BACNET_EXT_MULTI_OUT
ZCL_CLUST_BACNET_REG_MULTI_VALUE
ZCL_CLUST_BACNET_EXT_MULTI_VALUE
ZCL_FRAME_TYPE_MASK
Bits of frame type.
Referenced by zcl_command_dump.
ZCL_FRAME_TYPE_PROFILE
cmd acts across entire profile
Referenced by zcl_command_dump.
ZCL_FRAME_TYPE_CLUSTER
cmd is specific to a cluster
Referenced by zcl_comm_response.
ZCL_FRAME_TYPE_RESERVED1
ZCL_FRAME_TYPE_RESERVED2
ZCL_FRAME_GENERAL
mfg code field not present
ZCL_FRAME_MFG_SPECIFIC
mfg code field present
Referenced by zcl_invalid_command.
ZCL_FRAME_DIRECTION
direction bit
Referenced by zcl_command_dump.
ZCL_FRAME_CLIENT_TO_SERVER
cmd sent from client to server
Referenced by zcl_command_dump.
ZCL_FRAME_SERVER_TO_CLIENT
cmd sent from server to client
Referenced by zcl_comm_response.
ZCL_FRAME_DISABLE_DEF_RESP
default response only on error
Referenced by zcl_comm_response, zcl_command_dump.
ZCL_FRAME_RESERVED_BITS
should be set to 0
ZCL_STATUS_SUCCESS
ZCL_STATUS_FAILURE
ZCL_STATUS_NOT_AUTHORIZED
ZCL_STATUS_RESERVED_FIELD_NOT_ZERO
ZCL_STATUS_MALFORMED_COMMAND
ZCL_STATUS_UNSUP_CLUSTER_COMMAND
ZCL_STATUS_UNSUP_GENERAL_COMMAND
ZCL_STATUS_UNSUP_MANUF_CLUSTER_COMMAND
ZCL_STATUS_UNSUP_MANUF_GENERAL_COMMAND
ZCL_STATUS_INVALID_FIELD
ZCL_STATUS_UNSUPPORTED_ATTRIBUTE
ZCL_STATUS_INVALID_VALUE
ZCL_STATUS_READ_ONLY
ZCL_STATUS_INSUFFICIENT_SPACE
ZCL_STATUS_DUPLICATE_EXISTS
ZCL_STATUS_NOT_FOUND
ZCL_STATUS_UNREPORTABLE_ATTRIBUTE
ZCL_STATUS_INVALID_DATA_TYPE
ZCL_STATUS_INVALID_SELECTOR
ZCL_STATUS_WRITE_ONLY
ZCL_STATUS_INCONSISTENT_STARTUP_STATE
ZCL_STATUS_DEFINED_OUT_OF_BAND
ZCL_STATUS_HARDWARE_FAILURE
ZCL_STATUS_SOFTWARE_FAILURE
ZCL_STATUS_CALIBRATION_ERROR
ZCL_CMD_READ_ATTRIB
Read Attributes Command, payload is 1 to n 2-byte attribute IDs.
ZCL_CMD_READ_ATTRIB_RESP
Read Attributes Response Command, payload is 1 to n variable-length Read Attribute Status records (zcl_rec_read_attrib_status_t).
Referenced by zcl_time_client.
ZCL_CMD_WRITE_ATTRIB
Write Attributes Command, payload is 1 to n variable-length Write Attribute Record fields (same as zcl_attrib_t).
ZCL_CMD_WRITE_ATTRIB_UNDIV
Write Attributes Undivided Command, same payload as Write Attributes Command (zcl_attrib_t), but attributes are only written if all attributes can be written successfully.
ZCL_CMD_WRITE_ATTRIB_RESP
Write Attributes Response Command, payload is a single byte (ZCL_STATUS_SUCCESS) if all writes were successful or 1 to n 3-byte Write Attribute Status records (zcl_rec_write_attrib_status_t) for each write that failed.
Referenced by zcl_command_dump.
ZCL_CMD_WRITE_ATTRIB_NORESP
Write Attributes No Response Command, same payload as Write Attributes Command (ZCL_CMD_WRITE_ATTRIB), handled as a Write Attributes Command except the response is not sent.
ZCL_CMD_CONFIGURE_REPORT
ZCL_CMD_CONFIGURE_REPORT_RESP
ZCL_CMD_READ_REPORT_CFG
ZCL_CMD_READ_REPORT_CFG_RESP
ZCL_CMD_REPORT_ATTRIB
ZCL_CMD_DEFAULT_RESP
Default Response Command, payload is 2 bytes; Command ID and Status Code (zcl_default_response_t).
Referenced by zcl_command_dump.
ZCL_CMD_DISCOVER_ATTRIB
Discover Attributes Command, payload is 3 bytes; start attribute ID and maximum number of attributes to return (zcl_discover_attrib_t).
ZCL_CMD_DISCOVER_ATTRIB_RESP
Discover Attributes Response Command payload is a "discovery complete" byte (done = ZCL_BOOL_TRUE, more attributes = ZCL_BOOL_TRUE), followed by 1 to n 3-byte Attribute Report fields (zcl_rec_attrib_report_t).
ZCL_CMD_READ_STRUCT_ATTRIB
ZCL_CMD_WRITE_STRUCT_ATTRIB
ZCL_CMD_WRITE_STRUCT_ATTRIB_RESP
ZCL_ATTRIB_FLAG_NONE
ZCL_ATTRIB_FLAG_WRITEONLY
ZCL_ATTRIB_FLAG_READONLY
ZCL_ATTRIB_FLAG_HAS_MIN
ZCL_ATTRIB_FLAG_HAS_MAX
ZCL_ATTRIB_FLAG_REPORTABLE
ZCL_ATTRIB_FLAG_UNUSED1
ZCL_ATTRIB_FLAG_RAW
Data is stored as sent/received in ZCL requests (little-endian, 24-bit types stored as 3 bytes instead of 4).
Not applicable to string types.
ZCL_ATTRIB_FLAG_FULL
If set, this is part of a zcl_attribute_full_t structure.
ZCL_CMD_MATCH
Macro for checking the frame control field of a ZCL command.
Used to filter out commands that are (or are not) handled by the current function. p pointer to first byte of payload (typically envelope->payload when called from a standard ZCL command handler, or the address of frame_control from a zcl_command_t built with zcl_command_build) mfg either MFG_SPECIFIC or GENERAL dir either CLIENT_TO_SERVER or SERVER_TO_CLIENT type either PROFILE (e.g., general commands) or CLUSTER (cluster-specific command) TRUE ZCL command matches all three filters FALSE ZCL command does not match
Referenced by _zcl_basic_server, _zcl_onoff_handler, zcl_identify_command, zcl_time_client.
ZCL_CMD_IS_PROFILE
Identify profile commands (as opposed to cluster commands) using the frame control field of a ZCL command.
Ignores the manufacturer-specific bit (which specifies use of manufacturer-specific attributes). p pointer to first byte of payload TRUE ZCL command is not cluster-specific (profile command) FALSE ZCL command is cluster-specific
ZCL_CMD_IS_MFG_CLUSTER
Identify manufacturer-specific cluster commands using the frame control field of a ZCL command.
p pointer to first byte of payload TRUE ZCL command is manufacturer and cluster-specific FALSE ZCL command doesn't have the manufacturer-specific bit set, or is a profile-wide command
ZCL_CMD_IS_CLUSTER
Identify cluster commands that are not manufacturer-specific, using the frame control field of a ZCL command.
p pointer to first byte of payload TRUE ZCL command is manufacturer and cluster-specific FALSE ZCL command doesn't have the manufacturer-specific bit set, or is a profile-wide command
ZCL_DIRECTION_SEND
ZCL_DIRECTION_RECEIVE
ZCL_INDICATOR_INDICES_MASK
ZCL_INDICATOR_ACTION_MASK
ZCL_INDICATOR_REPLACE
ZCL_INDICATOR_ADD_ELEMENT
ZCL_INDICATOR_REMOVE_ELEMENT
ZCL_ATTR_WRITE_FLAG_NONE
ZCL_ATTR_WRITE_FLAG_ASSIGN
Assign the new value to the attribute (if not set, just checks the validity of the data).
Referenced by _zcl_identify_time_set.
ZCL_ATTR_WRITE_FLAG_WRITE_REQ
Parsing a Write Attribute Request record.
ZCL_ATTR_WRITE_FLAG_READ_RESP
Parsing a Read Attribute Response record.
ZCL_ATTRIBUTE_END_OF_LIST
Attribute ID for end of list marker.
Referenced by zcl_create_attribute_records, zcl_attribute_get_next.
ZCL_MFG_NONE
zcl_header_common_t
Common portion of ZCL header (appears after optional Manufacturer Code)
zcl_header_t
General header for casting onto an incoming frame.
Reference .type.mfg if (.frame_control & ZCL_FRAME_MFG_SPECIFIC != 0). Reference .type.std otherwise.
zcl_header_response_t
ZCL header structure used for building response frames that may or may not be manufacturer-specific.
Frame is sent starting with element .u.mfg.frame_control or .u.std.frame_control.
zcl_header_withmfg_t
ZLC header structure used when building a manufacturer-specific response frame.
zcl_header_nomfg_t
ZLC header structure used when building a normal (non-manufacturer-specific response frame.
zcl_attrib_t
General format for an attribute, used for Write Attributes and Report Attributes commands.
zcl_rec_read_attrib_resp_t
Used for ZCL_CMD_READ_ATTRIB_RESP.
zcl_rec_read_attrib_error_resp_t
zcl_rec_read_attrib_array_resp_t
zcl_rec_read_attrib_struct_resp_t
zcl_rec_write_attrib_status_t
Used for ZCL_CMD_WRITE_ATTRIB_RESP.
zcl_rec_report_send_t
zcl_rec_report_receive_t
zcl_rec_reporting_status_t
zcl_rec_read_report_cfg_t
zcl_rec_report_error_resp_t
zcl_rec_report_send_resp_t
zcl_rec_report_receive_resp_t
zcl_default_response_t
Used for ZCL_CMD_DEFAULT_RESP.
zcl_discover_attrib_t
Used for ZCL_CMD_DISCOVER_ATTRIB.
zcl_rec_attrib_report_t
Used for ZCL_CMD_DISCOVER_ATTRIB_RESP.
zcl_discover_attrib_resp_t
Used for ZCL_CMD_DISCOVER_ATTRIB_RESP.
zcl_selector_t
zcl_read_struct_attrib_t
zcl_rec_write_struct_attrib_t
zcl_rec_write_struct_attrib_resp_t
typedef uint_fast8_t(* zcl_attribute_update_fn) (const struct zcl_attribute_full_t FAR *entry))(const struct zcl_attribute_full_t FAR *entry)
Function pointer assigned to a ZCL attribute record, called to update the value of the given attribute.
Necessary for attributes that are tied to physical hardware (only updated when requested) or attributes that change over time (as with the ZCL Identify cluster).If the return value is not ZCL_STATUS_SUCCESS, the ZCL Read Attributes handler will return that as an error in the response frame. entry attribute to update ZCL_STATUS_SUCCESS successfully updated value ZCL_STATUS_HARDWARE_FAILURE unable to update value due to hardware problem ZCL_STATUS_SOFTWARE_FAILURE unable to update value due to software problem zcl_attribute_write_fn(), zcl_attribute_full_t
typedef int(* zcl_attribute_write_fn) (const struct zcl_attribute_full_t FAR *entry, zcl_attribute_write_rec_t *rec))(const struct zcl_attribute_full_t FAR *entry, zcl_attribute_write_rec_t *rec)
Function pointer assigned to a ZCL attribute record, called instead of zcl_decode_attribute() to process a Write Request for the attribute.
This function typically calls zcl_decode_attribute() to convert the request to a temporary variable and then perform additional checks on it before assigning to the actual variable. entry attribute to update rec record from Write Request with new value number of bytes consumed from Write Request zcl_attribute_update_fn(), zcl_attribute_full_t
uint8_t command
uint8_t payload[1][1]
first byte of variable-length field
PACKED_STRUCT
zcl_header_common_t common
mfg
manufacturer-specific extension
std
standard
uint8_t type
see zigbee/zcl_types.h
always ZCL_TYPE_STRUCTone of ZCL_TYPE_ARRAY, ZCL_TYPE_SET, ZCL_TYPE_BAGonly included if status == ZCL_STATUS_SUCCESS
Referenced by _zdo_match_desc_respond, zcl_encode_attribute_value, zcl_parse_attribute_record, zcl_print_array_value, zcl_print_struct_value, zcl_sizeof_type, zdo_send_bind_req.
uint8_t sequence
uint16_t mfg_code_le
uint8_t value[1][1]
variable length, depending on type
variable length, only if ZCL_STATUS_SUCCESS
uint8_t status
uint8_t element_type
uint16_t count_le
number of elements to follow
uint8_t elements[1][1]
mult. uint8_t type and variable-length value
uint16_t id_le
uint16_t attrib_id_le
uint8_t attrib_type
uint16_t min_interval_le
uint16_t max_interval_le
uint16_t timeout_period_le
uint8_t direction
zcl_rec_report_receive_t report_cfg
uint8_t max_return_count
zcl_rec_attrib_report_t attrib[1][1]
uint16_t index_le[15][15]
zcl_selector_t selector
uint16_t id
const zcl_attribute_tree_t FAR zcl_attributes_none[1][1]
If a cluster doesn't have attributes, use zcl_attributes_none (a single, empty attribute list) in the cluster definition.
Don't use NULL, since the APS dispatcher will use endpoint's context if the cluster's context is NULL.
const char * zcl_status_text(uint_fast8_t status)
Converts a ZCL status byte (one of the ZCL_STATUS_* macros) into a string.
status status byte to convert pointer to an unmodifiable string with a description of the status
Referenced by zcl_command_dump.
int zcl_command_build(zcl_command_t *cmd, const wpan_envelope_t FAR *envelope, zcl_attribute_tree_t FAR *tree)
Parse a ZCL request and store in a zcl_command_t structure with fields in fixed locations (therefore easier to use than the variable-length frame header).
Also uses the direction bit and manufacturer ID to search the attribute tree for the correct list of attributes. cmd buffer to store parsed ZCL command envelope envelope from received message tree pointer to attribute tree for cluster or NULL if the cluster doesn't have any attributes (typically passed in via endpoint dispatcher) 0 parsed payload from envelope into cmd -EINVAL invalid parameter passed to function -EBADMSG frame is too small for ZCL header's frame_control value
References FAR.
Referenced by _zcl_basic_server, _zcl_onoff_handler, zcl_general_command, zcl_identify_command, zcl_invalid_cluster, zcl_invalid_command, zcl_time_client.
void zcl_command_dump(const zcl_command_t *cmd)
Debugging routine that dumps contents of a parsed ZCL command structure to STDOUT.
cmd zcl_command_t structure populated by zcl_command_build()
References _TABLE_ENTRIES, zcl_command_t::command, FAR, zcl_command_t::frame_control, length, zcl_command_t::length, zcl_command_t::mfg_code, zcl_command_t::sequence, ZCL_CMD_DEFAULT_RESP, ZCL_CMD_WRITE_ATTRIB_RESP, ZCL_FRAME_CLIENT_TO_SERVER, ZCL_FRAME_DIRECTION, ZCL_FRAME_DISABLE_DEF_RESP, ZCL_FRAME_TYPE_MASK, ZCL_FRAME_TYPE_PROFILE, zcl_command_t::zcl_payload, zcl_status_text.
void zcl_envelope_payload_dump(const wpan_envelope_t *envelope)
Debugging routine that parses an envelope payload as a ZCL command and dumps a parsed copy to STDOUT.
envelope wpan_envelope_t structure with a ZCL command payload
int zcl_general_command(const wpan_envelope_t FAR *envelope, void FAR *context)
Handler for ZCL General Commands.
Used as the handler for attribute-only clusters (e.g., Basic Cluster), or called from a cluster's handler for commands it doesn't handle.Will send a Default Response for commands it can't handle.Currently does not support attribute reporting. envelope envelope from received message context pointer to attribute tree for cluster or NULL if the cluster doesn't have any attributes (typically passed in via endpoint dispatcher) 0 command was processed, including sending a possible response !0 error sending response or processing command
References zcl_command_build.
int zcl_invalid_cluster(const wpan_envelope_t FAR *envelope, wpan_ep_state_t FAR *ep_state)
Called if a request comes in for an invalid endpoint/cluster combination.
Sends a Default Response (ZCL_CMD_DEFAULT_RESP) of #ZCL_STATUS_FAILURE unless the received command was a Default Response or was broadcast. envelope envelope from received message ep_state pointer to endpoint's wpan_ep_state_t 0 command was a default response (and therefore ignored), or a default response was successfully sent !0 error sending response
References XBEE_UNUSED_PARAMETER, zcl_command_build, zcl_default_response.
int zcl_invalid_command(const wpan_envelope_t FAR *envelope)
Called if a request comes in for an invalid command on a valid endpoint/cluster combination.
Sends a Default Response (ZCL_CMD_DEFAULT_RESP) unless the received command was a Default Response or was broadcast. Depending on the command received, the response will be one of: ZCL_STATUS_UNSUP_CLUSTER_COMMANDZCL_STATUS_UNSUP_GENERAL_COMMANDZCL_STATUS_UNSUP_MANUF_CLUSTER_COMMANDZCL_STATUS_UNSUP_MANUF_GENERAL_COMMAND envelope envelope from received message 0 default response was successfully sent, or command did not require a default response !0 error building or sending response
References zcl_command_t::frame_control, status, zcl_command_build, ZCL_FRAME_MFG_SPECIFIC.
int zcl_build_header(zcl_header_response_t *rsp, zcl_command_t *cmd)
Support function to fill in a ZCL response header.
Set the frame_control, sequence and optional mfg_code fields of the ZCL response header, and return the offset to the actual start of the header (non-mfg specific skips the first two bytes). rsp buffer to store header of response cmd command we're responding to 0 responding to manufacturer-specific command 2 responding to non-manufacturer-specific command -EINVAL invalid parameter passed to function
int zcl_parse_attribute_record(const zcl_attribute_base_t FAR *entry, zcl_attribute_write_rec_t *write_rec)
Parse an attribute record from a Write Attributes Request or a Read Attributes Response and possibly store the new attribute value.
If ZCL_ATTR_WRITE_FLAG_READ_RESP is set in write_rec->flags, write_rec->buffer will be parsed as a Read Attributes Response record. Otherwise, it's parsed as a Write Attributes Request record. entry attribute table to search or NULL if there aren't any attributes on this cluster write_rec state information for parsing write request >=0 number of bytes consumed from buffer -EINVAL invalid parameter passed to function
References FAR, type.
int zcl_default_response(zcl_command_t *request, uint8_t status)
Send a Default Response (ZCL_CMD_DEFAULT_RESP) to a given command.
request command we're responding to status status to use in the response (see ZCL_STATUS_* macros under "ZCL Status Enumerations" in zigbee/zcl.h) 0 successfully sent response, or response not required (message was broadcast, sent to the broadcast endpoint, or sender set the disable default response bit) !0 error on send -EINVAL invalid parameter passed to function
References command, PACKED_STRUCT, status.
Referenced by zcl_invalid_cluster.
int zcl_check_minmax(const zcl_attribute_base_t FAR *entry, const uint8_t FAR *buffer_le)
Checks whether a new value from a Write Attributes command is within the limits specified for a given attribute.
entry entry to use for min/max check buffer_le buffer with new value (in little-endian byte order), from write attributes command 0 new value is within range (or attribute doesn't have a min/max) -EINVAL invalid parameter passed to function !0 value is out of range
References FAR, value.
uint32_t zcl_convert_24bit(const void FAR *value_le, bool_t extend_sign)
Convert a 24-bit (3-byte) little-endian value to a 32-bit value in host byte order.
value_le pointer to 3 bytes to convert extend_sign if TRUE, set high byte of result to 0xFF if top bit of 24-bit value is set A 32-bit, host-byte-order version of the 24-bit, little-endian value passed in.
References FAR.
int zcl_decode_attribute(const zcl_attribute_base_t FAR *entry, zcl_attribute_write_rec_t *rec)
Decode attribute value from a Write Attribute Request or Read Attribute Response record and optionally write to entry.
entry entry from attribute table rec state information for parsing write request >=0 number of bytes consumed from rec->buffer -EINVAL invalid parameter passed to function
References FAR, length.
Referenced by _zcl_identify_time_set.
int zcl_encode_attribute_value(uint8_t FAR *buffer, int16_t bufsize, const zcl_attribute_base_t FAR *entry)
Format a ZCL attribute's value for a Read Attributes Response or a Write Attributes Request.
Copies the value of attribute entry to buffer in little-endian byte order. Will not write more than bufsize bytes. Used to build ZCL frames. buffer buffer to store encoded attribute bufsize number of bytes available in buffer entry attribute to encode into buffer -ZCL_STATUS_SOFTWARE_FAILURE invalid parameter passed in -ZCL_STATUS_DEFINED_OUT_OF_BAND ghost attribute with NULL value -ZCL_STATUS_INSUFFICIENT_SPACE buffer too small to encode value -ZCL_STATUS_FAILURE unknown/unsupported attribute type -ZCL_STATUS_HARDWARE_FAILURE failure updating attribute value -ZCL_STATUS_SOFTWARE_FAILURE failure updating attribute value >=0 number of bytes written
References FAR, status, type.
Referenced by zcl_create_attribute_records.
const zcl_attribute_base_t FAR * zcl_attribute_get_next(const zcl_attribute_base_t FAR *entry)
Return a pointer to the next attribute entry from an attribute table.
entry current entry from the table NULL entry was NULL !NULL pointer to next attribute record If entry points to the last entry in the table, this function will return the same address instead of advancing off the end of the table. zcl_find_attribute
References ZCL_ATTRIBUTE_END_OF_LIST.
Referenced by zcl_create_attribute_records.
const zcl_attribute_base_t FAR * zcl_find_attribute(const zcl_attribute_base_t FAR *entry, uint16_t search_id)
Search the attribute table starting at entry, for attribute ID search_id.
entry starting entry for search search_id attribute ID to look for NULL attribute id search_id not in list !NULL pointer to attribute record
int zcl_send_response(zcl_command_t *request, const void FAR *response, uint16_t length)
Send a response to a ZCL command.
Uses information from the command received to populate fields in the response. request command to respond to response payload to send as response length number of bytes in response 0 successfully sent response !0 error on send