zcl_client.c
zcl_client_debug
zcl_format_utctime_fn zcl_format_utctime
Pointer to function that converts a zcl_utctime_t value to a human-readable timestamp.
Defaults to a function that formats timestamps as "YYYY-MM-DD HH:MM:SS UTC" or "[Invalid Timestamp] if utctime is 0xFFFFFFFF. Can be overriden by the user program to a function that uses another format. Strings must be limited to 40 characters. dest buffer to hold the formatted string utctime time value to format Value of parameter dest.
int zcl_process_read_attr_response(zcl_command_t *zcl, const zcl_attribute_base_t FAR *attr_table)
Process a Read Attributes Response and populate the attibute values into an attribute table as if it was a Write Attributes Request.
Used in ZCL clients that want to read a lot of ZCL attributes. The client has a mirrored copy of the attributes on the target, and this function is used to populate that copy using the Read Attributes Responses. zcl ZCL command to process attr_list start of the attribute list to use for storing attribute responses ZCL status value to send in a default response
References FAR.
int zcl_client_read_attributes(wpan_envelope_t FAR *envelope, const zcl_client_read_t *client_read)
Send a Read Attributes request for attributes listed in client_read.
envelope addressing information for sending a ZCL Read Attributes request; this function fills in the payload and length client_read data structure used by ZCL clients to do ZDO discovery followed by ZCL attribute reads 0 successfully sent request !0 error sending request
References FAR, PACKED_STRUCT.
int _zcl_send_read_from_zdo_match(wpan_conversation_t FAR *conversation, const wpan_envelope_t FAR *envelope)
Process responses to ZDO Match_Desc broadcast sent by zdo_send_match_desc() and generate ZCL Read Attributes request for the attributes in the related conversation's context (a pointer to a zcl_client_read_t object).The Read Attributes Responses are handled by the function registered to the cluster in the endpoint table. conversation matching entry in converstation table (which contains a context pointer) envelope envelope of response or NULL if conversation timed out 0 send ZCL request for current time !0 error sending ZCL request for current time Todosupport a flag in the client_read object for sending ZCL request to first endpoint in list (current behavior) or all endpoints (for example, to query ALL meter endpoints on ALL radios).Todofind a way to track whether frame came in from broadcast or unicast response if unicast, can return WPAN_CONVERSATION_END
References endpoint, FAR, PACKED_STRUCT.
Referenced by zcl_find_and_read_attributes.
int zcl_find_and_read_attributes(wpan_dev_t *dev, const uint16_t *clusters, const zcl_client_read_t FAR *cr)
Use ZDO Match Descriptor Requests to find devices with a given profile/cluster and then automatically send a ZCL Read Attributes request for some of that cluster's attributes.
dev device to use for time request clusters pointer to list of server clusters to search for, must end with WPAN_CLUSTER_END_OF_LIST cr zcl_client_read record containing information on the request (endpoint, attributes, etc.); must be a static object (not an auto variable) since the ZDO responder will need to access it 0 request sent !0 error sending request
References _zcl_send_read_from_zdo_match, zdo_send_match_desc.
int zdo_send_match_desc(wpan_dev_t *dev, const uint16_t *clusters, uint16_t profile_id, wpan_response_fn callback, const void FAR *context)
Send a ZDO Match Descriptor request for a list of cluster IDs.
dev device to use for time request clusters pointer to list of server clusters to search for, must end with WPAN_CLUSTER_END_OF_LIST profile_id profile ID associated with the cluster IDs (cannot be WPAN_APS_PROFILE_ANY) callback function that will process the ZDO Match Descriptor responses; see wpan_response_fn for the callback's API context context to pass to callback in the wpan_conversation_t structure 0 request sent !0 error sending request zcl_find_and_read_attributes() Todoupdate API to allow for unicast request in addition to broadcast
References _WPAN_IEEE_ADDR_BROADCAST, wpan_envelope_t::cluster_id, wpan_envelope_t::dev, EINVAL, wpan_envelope_t::ieee_address, wpan_envelope_t::network_address, WPAN_NET_ADDR_BCAST_NOT_ASLEEP, WPAN_NET_ADDR_UNDEFINED, ZDO_MATCH_DESC_REQ, zdo_match_desc_request.
Referenced by zcl_find_and_read_attributes.
int zcl_create_attribute_records(void FAR *buffer, uint8_t bufsize, const zcl_attribute_base_t FAR **p_attr_list)
From a list of attributes, write ID (in little-endian byte order), type and value to a buffer as would be done in a Write Attributes Request.
The attribute list should be an array of attribute records, ending with an attribute ID of ZCL_ATTRIBUTE_END_OF_LIST. buffer buffer to write values to bufsize size of buffer p_attr_list pointer to the attribute list to encode in buffer; points to next attribute to encode if buffer is filled number of bytes written to buffer
References FAR, htole16, ZCL_ATTRIBUTE_END_OF_LIST, zcl_attribute_get_next, zcl_encode_attribute_value.
int zcl_send_write_attributes(wpan_envelope_t *envelope, const zcl_attribute_base_t FAR *attr_list)
Send one or more Write Attributes Requests to a node on the network.
This function API and is likely to change in a future release to include a Manufacturer ID and flags for sending server-to-client and "undivided" write requests. envelope envelope to use for sending request; payload and length cleared on function exit attr_list attributes with values to send a Write Attributes Request for -EINVAL NULL parameter passed, or couldn't find source endpoint based on envelope <0 error trying to send request (for large writes, one or more requests may have been successful) 0 request(s) sent
const char* _zcl_format_utctime(char dest[40], zcl_utctime_t utctime)
Default function for zcl_format_utctime function pointer.
int zcl_print_array_value(const void *value, int value_length)
Print Read Attributes Response value of an array attribute.
Helper function for zcl_print_attribute_value(), takes a pointer to the "value" field of a Read Attributes Response for an array type, formats it and prints to stdout.Example: of3UNSIGNED_8BIT [0]=0x54=84 [1]=0x42=66 [2]=0x43=67 value pointer to ZCL-encoded array value value_length number of bytes at value -EINVAL value is NULL or is too small >=3 number of bytes from value consumed by function zcl_print_attribute_value, zcl_print_struct_value
References EINVAL, type, value, zcl_print_attribute_value, zcl_type_name.
int zcl_print_struct_value(const void *value, int value_length)
Print Read Attributes Response value of a structure attribute.
Helper function for zcl_print_attribute_value(), takes a pointer to the "value" field of a Read Attributes Response for a structure type, formats it and prints to stdout.Example: with3elements .element0(TIME_UTCTIME)=2012-01-0100:00:00 .element1(UNSIGNED_8BIT)=0xAA=170 .element2(SIGNED_8BIT)=0xAA=-86 value pointer to ZCL-encoded structure value value_length number of bytes at value -EINVAL value is NULL or is too small >=2 number of bytes from value consumed by function zcl_print_attribute_value, zcl_print_array_value
References EINVAL, type, value, zcl_print_attribute_value, zcl_type_name.
int zcl_print_attribute_value(uint8_t type, const void *value, int value_length)
Formats an attribute value and prints it to stdout.
type ZCL datatype of attribute's value value pointer to the ZCL-encoded value value_length number of bytes at value -EINVAL value is NULL or is too small >=2 number of bytes from value consumed by function zcl_print_array_value, zcl_print_struct_value
Referenced by zcl_print_array_value, zcl_print_struct_value.